### ISSUE TITLE
@Property as meta-annotation

### ISSUE THREAD

**Issue by ledoyen** [micronaut-projects/micronaut-test#10]
A test class can be annotated with `@Property`, however when used as a meta-annotation, it is ignored.

The change can be done in `AbstractMicronautExtension#beforeClass`, but in (at least) two ways:
- add **junit-platform-commons** in the compilePath to be able to use `AnnotationSupport#findRepeatableAnnotations` in **test-core**
- copy the JUnit method in an utility class in **test-core** (with minor adjustements to avoid referencing JUnit classes like `Preconditions`)
- ...

@graemerocher what are your thoughts about this ?

**Comment by graemerocher** [comment]
The method would need to be copied since we support both Junit and Spock

**Comment by graemerocher** [comment]
Thanks, I have released 1.0.1 that includes your 2 PRs

**Comment by ledoyen** [comment]
Thanks a lot !
