### ISSUE TITLE
RequestSpecificationFactory ignores property micronaut.test.server.url

### ISSUE THREAD

**Issue by cogam** [micronaut-projects/micronaut-test#1006]
### Expected Behavior

Hello, I want to write an integration test of an external server using RestAssured.

I have a test class with these annotations and test methods:

```java
@MicronautTest(startApplication = false)
@Property(name = "micronaut.test.server.url", value = "${myoptions.url}")
public class MyIntegrationTest {
//...

  @Test
  void myTestCase(RequestSpecification spec) {
    spec.given().log().all()
     .when().get("/api")
    // ...
  }
}
```

My configuration sets myoptions.url to for example:

```yml
myoptions:
  url:
    http://external-server:8080
```

I expect to see logs with requests to `http://external-server:8080/api`.

Is it beyond the scope of the RestAssured utility? As a workaround I try to set the full URL including server and port, not just a host-relative URL.

### Actual Behaviour

I actually see logs with requests to `http://localhost:8080/api`. The spec ignores the value of `micronaut.test.server.url`. Injecting and printing the value of either `micronaut.test.server.url` or `myoptions.url` shows that they hold the external server url.

### Steps To Reproduce

Create a minimal test class against an existing API as above and run. Verify the log output. If needed, I can add a minimal example.

### Environment Information

- OS: Ubuntu 22.04.LTS
- Java 20

### Version

4.3.4

Thank you for your time!

**Comment by sdelamo** [comment]
This is where the RequestSpecification is created: 

https://github.com/micronaut-projects/micronaut-test/blob/4.4.x/test-rest-assured/src/main/java/io/micronaut/test/rest/assured/RequestSpecificationFactory.java

It uses the embedded server url not a url coming from a property. 

Why were you expecting `micronaut.test.server.url` to work? Is that documented?

**Comment by cogam** [comment]
@sdelamo thank you for your response. I read the documentation on [Testing External Servers](https://micronaut-projects.github.io/micronaut-test/latest/guide/#junit5TestingExternalServers), last paragraph. Maybe I interpreted too much into it.

> Alternatively if you have independently started an EmbeddedServer instance programmatically you can also specify the URL to the server with the micronaut.test.server.url property.



Ok so the injected `RequestSpecification` works as intended. But then, what does change by setting this property?

**Comment by sdelamo** [comment]
Maybe we can in https://github.com/micronaut-projects/micronaut-test/blob/4.4.x/test-rest-assured/src/main/java/io/micronaut/test/rest/assured/RequestSpecificationFactory.java if the `micronaut.test.server.url` is available and we can change the instantiation of `RequestSpecification` in this case. 

@timyates can you look into this? Maybe we can add a test for https://jsonplaceholder.typicode.com
