### ISSUE TITLE
Micronaut Spock bootstraps embedded server multiple times

### ISSUE THREAD

**Issue by sjrd218** [micronaut-projects/micronaut-test#105]
Micronaut appears to run it's internal Spec setup multiple times when running a Micronaut Spock test that has an abstract Specification class as it's parent.

This causes a problem with the EmbeddedServer bootstrap. I have set the port for the test EmbeddedServer to a specific port using application-test.yml, and since Micronaut is trying to create the EmbeddedServer multiple times, it fails with a port is in use error. 

Since the field is marked as `@Shared` I do not expect the server to be created multiple times.

I have linked to a project that demonstrates the problem.

Note: If the port is not set in application-test.yml the test works fine, but this doesn't work for my case because I need the embedded server to run on the port I'm specifying.

### Steps to Reproduce

1. clone the bug report project at: https://github.com/sjrd218/micronaut-embedded-bug
2. run: ./gradlew test
3. see errors saying the port is in use

### Expected Behaviour

A `@Shared` field should not be recreated.
Also the NettyHttpServer is marked as a `@Singleton` so I didn't expect Micronaut to try to recreate it.

I expected the test to bootstrap one EmbeddedServer that I could hit in my test.

### Actual Behaviour

Test fails with port already in use exception

### Environment Information

- **Operating System**: Mac 10.13.6
- **Micronaut Version:** 1.2.8
- **JDK Version:** OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_222-b10)

**Comment by jameskleeh** [comment]
I'm not sure about the feasibility of having the `@MicronautTest` annotation on a super class. Currently the annotation must be on each subclass. In your example if you move the annotation to `MyControllerTest` the test passes

**Comment by sjrd218** [comment]
Moving the `@MicronautTest` annotation from the super class prevents me from using Micronaut injected beans in the super class's `setupSpec` because spock won't let you use non `@Shared` fields in the `setupSpec` method.

If you put `@MicronautTest` on the subclass, the bean isn't injected into the `@Shared` field in the super class and you get an NPE for anything you're trying to setup on the bean in the `setupSpec` of the super class.

**Comment by jameskleeh** [comment]
@sjrd218 Thanks for the explanation. Seems like a reasonable use case

**Comment by alvarosanchez** [comment]
The injection needs to be done at the `@MicronautTest` level. That said, you can still benefit from reusing code in a parent class:

```groovy
class MyAbstractSpec extends Specification {

    @Shared
    abstract EmbeddedServer server

    def setupSpec() {
        println "do some setup stuff here"
    }
}

@MicronautTest
class MyControllerSpec extends MyAbstractSpec {

    @Inject
    EmbeddedServer server

    def "Info"() {
        setup:
        RxHttpClient client = RxHttpClient.create(UriBuilder.of("http://localhost:${server.port}").build().toURL())
        expect:
        client.retrieve("/").blockingFirst() == MyController.INFO_STR

    }
}
```
