### ISSUE TITLE
Include test dependencies as part of io.micronaut:micronaut-bom

### ISSUE THREAD

**Issue by x80486** [micronaut-projects/micronaut-test#12]
I'm importing `io.micronaut:micronaut-bom:1.0.1` as part of the `dependencyManagement` block in a Gradle script.

If I specify: `testImplementation("io.micronaut.test:micronaut-test-junit5")`, it's not getting resolved, I have to specify the same version: `1.0.1`. It might be because the dependency notation (read: group, name, etc.) doesn't match with the one in the BOM, but I think it would be nice if it's included. Not sure if you would have to rename something.

Thanks in advance!

**Comment by graemerocher** [comment]
This was fixed by https://github.com/micronaut-projects/micronaut-core/commit/4e52f2b7c0476ef3db2bca229807a7512b22bf88
