### ISSUE TITLE
Update kotlintest to kotest

### ISSUE THREAD

**Issue by ashishkujoy** [micronaut-projects/micronaut-test#120]
Recently with 4.0.0-BETA1 release kotlintest has been renamed to [kotest](https://github.com/kotest/kotest). As a result micronaut-test-kotlintest extension is not able to compile with kotest.
To make it work with 4.0.0-BETA1 or anyother future release we need to update kotlintest dependency and update all imports from ```io.kotlintest```  to ```io.kotest```

**Comment by meamZ** [comment]
This would be great to see since now kotest is out of beta
