### ISSUE TITLE
Micronaut test dosen't seem to run micronaut.run(..)

### ISSUE THREAD

**Issue by BenStuart** [micronaut-projects/micronaut-test#127]
I need to run `ApiContextInitializer.init()` but when running in test mode `./gradlew test` the application dosen't seem to start from the entrypoint `application.main()`. Is there a way to get the tests to run  `ApiContextInitializer.init()` beforehand?
```
public class Application {
    public static void main(String[] args) {
        //Startup Telegram bot, this init() needs to execute before micronaut
        ApiContextInitializer.init();
        //Start Micronaut
        Micronaut.run(Application.class);
    }
}
```

I know there was `@before` and `@After` annotations for Junit tests but that doesn't seem to be used anymore.

**Comment by graemerocher** [comment]
This is correct. If you want to do init somewhere use an `@EventListener` for `StartupEvent`
