### ISSUE TITLE
Failing tests with multiple JPA Database connection

### ISSUE THREAD

**Issue by picaso** [micronaut-projects/micronaut-test#128]
We are running into this weird issue!

To reproduce: 
- Just create a sample project with multiple data sources using JPA
- Create an empty @micronatTest to force context building
- Create application-test YAML pointing to the two data sources for testing
- It will fail 100% of the time unless you specify @MicronautTest(transactional=false)

**Comment by alvarosanchez** [comment]
I created https://github.com/alvarosanchez/micronaut-test-issue-128 and cannot reproduce the issue.
