### ISSUE TITLE
Tests are ignored when using JUnit5 & Micronaut Test

### ISSUE THREAD

**Issue by bbarin** [micronaut-projects/micronaut-test#14]
Tests are skipped using JUnit5, Micronaut test and Mocking Beans.

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. create an app via mn-cli
2. Follow the guide to add JUnit5 support (https://micronaut-projects.github.io/micronaut-test/latest/guide/index.html#junit5)
3. Add `testCompile "org.junit.jupiter:junit-jupiter-engine:5.1.0"` otherwise tests don't compile via Gradle
4. Create a test like:

```
@MicronautTest
public class ControllerTest {

    @Inject
    Dependency dependency;

    @Test
    public void hello() {
        dependency.doSomething();
        System.out.println("Topzera");
    }

    @MockBean(Dependency.class)
    Dependency another() {
        return Mockito.mock(Dependency.class);
    }
}
```

5. Run gradle 

### Expected Behaviour

Test should pass ( or at least get executed)

### Actual Behaviour

Tests are skipped running via Gradle 

### Environment Information

- **Operating System**: Fedora 29
- **Micronaut Version:** 1.0.3
- **JDK Version:** 11

### Example Application

- https://github.com/bbarin/micronaut-test-issue.git

**Comment by bbarin** [comment]
Great! works fine now. Perhaps it's useful to add this to the documentation. I will fork and open a PR

**Comment by graemerocher** [comment]
Thanks for the feedback!

**Comment by bbarin** [comment]
https://github.com/micronaut-projects/micronaut-test/pull/15

**Comment by graemerocher** [comment]
In the next version this will cause an error instead of ignoring the test https://github.com/micronaut-projects/micronaut-test/commit/5ed34ccf019dbda7b1460d0d654a083bda6f7451
