### ISSUE TITLE
Get ApplicationContext in a JUnit5 extension

### ISSUE THREAD

**Issue by rmpestano** [micronaut-projects/micronaut-test#145]
Guys, is it possible to lookup Micronaut application context **inside a JUnit5 extension**? 

For example Spring stores it's context in the [JUnit5 store](https://junit.org/junit5/docs/5.0.0/api/org/junit/jupiter/api/extension/ExtensionContext.Store.html) so it can be [retrieved later](https://github.com/database-rider/database-rider/blob/b03cf80002ab82e7f918aa56aa8852896f3bac77/rider-junit5/src/main/java/com/github/database/rider/junit5/DBUnitExtension.java#L136-L138). 

Is it possible to have something like that for Micronaut JUnit5 extension?

Thanks in advance!

**Comment by graemerocher** [comment]
`@Inject ApplicationContext applicationContext`

**Comment by rmpestano** [comment]
Hi, I need to get It inside a JUnit extension where there is not injection support, can you look into the sample link I provided?

Thanks

**Comment by graemerocher** [comment]
Oh I see. Yeah not possible yet, but seems like something we should support. Contributions welcome!

**Comment by rmpestano** [comment]
Alright, good to know, I'll see if I can help.
