### ISSUE TITLE
private modified breaks bean mocking with Spock

### ISSUE THREAD

**Issue by szpak** [micronaut-projects/micronaut-test#147]
Based on one of your tests:
```
@MicronautTest
class MathCollaboratorSpec extends Specification {

    @Inject
    private MathService mathService // <-- private here breaks the test

    @Inject
    @Client('/')
    RxHttpClient client // <3>

    @Unroll
    void "should compute #num to #square"() {
        when:
        Integer result = client.toBlocking().retrieve(HttpRequest.GET('/math/compute/10'), Integer) // <3>

        then:
        1 * mathService.compute(10) >> Math.pow(num, 2)  // <4>
        result == square

        where:
        num | square
        2   | 4
        3   | 9
    }

    @MockBean(MathServiceImpl) // <1>
    MathService mathService() {
        Mock(MathService)
    }

}
```

When `private` is added to a collaborator which is also mocked with `@MockBean` it start to fail - here with "Page not found", but it is due to null response. Stubbing in the `mathService()` method works (i.e. it taken into account):
```
        Mock(MathService) {
            compute(10) >> 42
        }

```

After a brief analysis, it seems that an other object is injected or it is done in wrong order as stubbing in a test method doesn't work - controller doesn't see it. When stubbed in `mathService()` it works fine.

Adding private to `client` doesn't affect testing. It doesn't affect also a variant with JUnit 5. Tested with the version in `master`.

**Comment by graemerocher** [comment]
The use of private requires reflection which Micronaut doesn't support. Use constructor injection if you need private.

**Comment by szpak** [comment]
Hmm, constructor injection in a test class is problematic - JUnit/Spock manages the class creation (it's not a production class).

I wonder why it still works with JUnit?

**Comment by szpak** [comment]
Also `private RxHttpClient client` also works.
