### ISSUE TITLE
Improve DI lifecycle handling

### ISSUE THREAD

**Issue by brandonlamb** [micronaut-projects/micronaut-test#16]
Not sure what a good issue title is exactly...

1. This micronaut-test is awesome! Great work!
1. My team was going down the TestNG route. We were having to implement Registry (as Singleton) pattern to copy dependencies out of appContext, blah blah. It was working, but hacky.
1. We have since switched our prototype functional tests to micronaut-test, love it! Much cleaner

An observation

```kotlin
@MicronautTest
class MyTest {
  @Inject
  lateinit var foo: Foo

  @BeforeAll
  fun setUp() {
    foo.bar()
  }
}
```

I am finding that I cannot use @BeforeAll because of probably lifecycle order? The lateinit vars are not yet initialized when the `@BeforeAll` runs, which kinda defeats the purpose?

**Comment by graemerocher** [comment]
See https://github.com/micronaut-projects/micronaut-test/blob/master/test-junit5/src/test/java/io/micronaut/test/junit5/InjectSharedTest.java for an example how to do this
