### ISSUE TITLE
MicronautTest requires @Inject when Micronaut does not

### ISSUE THREAD

**Issue by mmindenhall** [micronaut-projects/micronaut-test#19]
When micronaut-test was first announced, we tried to refactor some of our tests to use it.  We couldn't get it working, so we bailed.  Today I spent some more time on this, and realized that there are some inconsistencies between how things work in regular Micronaut beans vs. test classes annotated with `@MicronautTest`.

Here's one thing that tripped us up.

In my controller, I can directly inject a property from my `application.yml` as follows:

```groovy
    $Value('${foo.bar.bat}')
    String myStr
```

However, I need to add `@Inject` for this to work within a `@MicronautTest`:

```groovy
    @Inject
    $Value('${foo.bar.bat}')
    String myStr
```

The documentation is very confusing here, because the `io.micronaut.test.spock.PropertySpec` is used as an example in the guide, and in that example, `@Value` works without `@Inject`.  But the next example (using property sources) shows `@Property` with `@Inject`, which is where I got the idea to try `@Value` with `@Inject` as above.

It would be very helpful to either fix this in the code, or make it clear in the docs how (and why) it differs from bean injection in micronaut-core.

**Comment by jameskleeh** [comment]
We have a test for this. If you are still experiencing this in the latest version, please add a comment here and I'll reopen
