### ISSUE TITLE
Add annotation parameter to @MicronautTest to start only Application context not embedded server

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-test#213]
Currently, I think when you annotate a test with `@MicronautTest` we start a `EmbeddedServer`. It would be nice to have an attribute to say, don't start the server just the application context. Maybe something like: 

`@MicronautTest(server= false)`

**Comment by nhoughto** [comment]
For us, this would be the default. Tests that make requests over the network are separate from `@MicronautTest` tests which are more unit tests, so we basically never use the start that is started.

**Comment by sdelamo** [comment]
I would prefer `@Micronaut(server=false)` to be the default but it will be a breaking change.

**Comment by ilopmar** [comment]
@nhoughto you can create your own meta-annotation with the defaults you want and use them instead of `@MicronautTest`: https://docs.micronaut.io/latest/guide/index.html#metaScopes

**Comment by nhoughto** [comment]
ah makes sense thanks for the tip, so if the `server` property gets added, i can disable it by default 👍
