### ISSUE TITLE
Create micronaut-test BOM

### ISSUE THREAD

**Issue by ctoestreich** [micronaut-projects/micronaut-test#23]
Similar to how the micronaut bom is created, there should be a micronaut test bom as this grows to more libraries:

Example
```xml
<dependency>
    <groupId>io.micronaut.test</groupId>
    <artifactId>micronaut-test-bom</artifactId>
    <version>${micronaut.test.version}</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
```

**Comment by brandonlamb** [comment]
Would this mean I wouldn't have to specify dependencies for things like junit-platform and whatnot? 👍  if so

**Comment by jameskleeh** [comment]
I think we'll just include these libraries in the core bom to keep things simple
