### ISSUE TITLE
Setup / cleanup methods run in separate transaction and are always commited

### ISSUE THREAD

**Issue by angelyan** [micronaut-projects/micronaut-test#238]
This is clear from the implementation of the methods [interceptBeforeEachMethod](https://github.com/micronaut-projects/micronaut-test/blob/v1.2.2/test-junit5/src/main/java/io/micronaut/test/extensions/junit5/MicronautJunit5Extension.java#L65) and [interceptAfterEachMethod](https://github.com/micronaut-projects/micronaut-test/blob/v1.2.2/test-junit5/src/main/java/io/micronaut/test/extensions/junit5/MicronautJunit5Extension.java#L72) in [MicronautJunit5Extension](https://github.com/micronaut-projects/micronaut-test/blob/v1.2.2/test-junit5/src/main/java/io/micronaut/test/extensions/junit5/MicronautJunit5Extension.java), which end up executing `SpringTransactionTestExecutionListener#afterTestExecution(false)` [here](https://github.com/micronaut-projects/micronaut-test/blob/v1.2.2/test-core/src/main/java/io/micronaut/test/transaction/spring/SpringTransactionTestExecutionListener.java#L66) and [here](https://github.com/micronaut-projects/micronaut-test/blob/v1.2.2/test-core/src/main/java/io/micronaut/test/transaction/spring/SpringTransactionTestExecutionListener.java#L76).

The result is that the following tests (written from [JpaRollbackTest.java](https://github.com/micronaut-projects/micronaut-test/blob/v1.2.2/test-junit5/src/test/java/io/micronaut/test/junit5/JpaRollbackTest.java)) fail when ran together:

```java
@MicronautTest
@DbProperties
public class JpaRollbackTest {

    @Inject
    EntityManager entityManager;

    @BeforeEach
    void setUp() {
        final Book book = new Book();
        book.setTitle("The Stand");
        entityManager.persist(book);
        assertNotNull(entityManager.find(Book.class, book.getId()));
    }

    @Test
    void testPersistOne() {
        final CriteriaQuery<Book> query = entityManager.getCriteriaBuilder().createQuery(Book.class);
        query.from(Book.class);
        assertEquals(1, entityManager.createQuery(query).getResultList().size());
    }

    @Test
    void testPersistTwo() {
        final CriteriaQuery<Book> query = entityManager.getCriteriaBuilder().createQuery(Book.class);
        query.from(Book.class);
        assertEquals(1, entityManager.createQuery(query).getResultList().size());
    }
}
```

```
Expected :
1
Actual :
2
java.lang.AssertionError: expected:<1> but was:<2>
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:834)
at org.junit.Assert.assertEquals(Assert.java:645)
at org.junit.Assert.assertEquals(Assert.java:631)
at io.micronaut.test.junit5.JpaRollbackTest.testPersistTwo(JpaRollbackTest.java:55)
```

Is this the expected behavior?

**Comment by graemerocher** [comment]
Currently expected as it allows you to setup test data before test is run and tear it down, otherwise there is no other way to do that. If you want the changes to be rolled back invoke the setup within the method.

**Comment by angelyan** [comment]
Do you think it would be a good idea to be able to customize this behavior through an annotation parameter?

Something like:
```java
@MicronautTest(rollbackSetup = true)
```

**Comment by alvarosanchez** [comment]
I'm not sure the value it would bring, since your example can be made to pass by simply:

```java
@MicronautTest
@DbProperties
public class JpaRollbackTest {

    @Inject
    EntityManager entityManager;

    void setUp() {
        final Book book = new Book();
        book.setTitle("The Stand");
        entityManager.persist(book);
        assertNotNull(entityManager.find(Book.class, book.getId()));
    }

    @Test
    void testPersistOne() {
        setUp();
        final CriteriaQuery<Book> query = entityManager.getCriteriaBuilder().createQuery(Book.class);
        query.from(Book.class);
        assertEquals(1, entityManager.createQuery(query).getResultList().size());
    }

    @Test
    void testPersistTwo() {
        setUp();
        final CriteriaQuery<Book> query = entityManager.getCriteriaBuilder().createQuery(Book.class);
        query.from(Book.class);
        assertEquals(1, entityManager.createQuery(query).getResultList().size());
    }
}
```

**Comment by angelyan** [comment]
I think the value would be precisely not having to do that, since needing to call the setup method explicitly in each test kind of defeats the purpose of the `@BeforeEach` annotation.

**Comment by ilopmar** [comment]
@angelyan personally I think is a _code smell_ to share test data among different tests. This can only lead to test leakage in the whole test suite that will be really complicated to track down.
I always write my tests isolated from each other and if in a test I create some data, I make sure that the test itself cleans up everything, so the next test has an empty db. I even enforce that so if there is a data leakage in some test, the test itself fails, so I can fix the leakage.

**Comment by graemerocher** [comment]
@ilopmar your statement seems to reinforce what @angelyan wants which I imagine is for the changes to be rolled back for each `@BeforeEach`. However the way test frameworks extensions work for JUnit 5 and Spock that is not possible since it is not possible for the `@BeforeEach` method to run in the same transaction as the test method.

The best we could possibly offer is a way to disable this behaviour, but I am not sure that is really necessary because you can already do:

`@MicronautTest(transactional=false)` 

And add whatever transaction handling behaviour you want.

**Comment by ilopmar** [comment]
What I was trying to say is that all tests should be independent from each other and using `@BeforeEach` or Spock's `setup` or `setupSpec` for creating the same data in all the tests should be discouraged.

Probably a bad choice of words on my side. Sorry about that...

**Comment by angelyan** [comment]
@graemerocher maybe there's something I'm missing, but I was able to get it to work by changing `SpringTransactionTestExecutionListener` so that it keeps the transaction used in the `@BeforeEach` open and doesn't start a new one before executing the test. Is there something wrong with that approach?

**Comment by graemerocher** [comment]
That may work for JUnit. Not sure about Spock. Either way there would need to be some transaction cleanup to close the connection after each test is run

**Comment by angelyan** [comment]
Definitely. I tested it with Spock and it seems to work just fine.
