### ISSUE TITLE
MicronautTest with Testcontainers (JUnit5) @BeforeAll

### ISSUE THREAD

**Issue by jevin36** [micronaut-projects/micronaut-test#26]
Hi,
in my test setup I am having JUnit5, Micronaut-Test and Testcontainers. I'd like to run an integration test against rabbitmq. I got it done without @MicronautTest but I am having problems integrating @MicronautTest. The problem is, that @MicronautTest triggers its setup even before @BeforeAll or a local static{} . 

Especially with @Testcontainers it leads to a problem. This is my test class:

```
import io.micronaut.context.ApplicationContext;
import io.micronaut.context.env.PropertySource;
import io.micronaut.core.util.CollectionUtils;
import io.micronaut.runtime.server.EmbeddedServer;
import io.micronaut.test.annotation.MicronautTest;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.testcontainers.containers.GenericContainer;
import org.testcontainers.junit.jupiter.Testcontainers;
import org.testcontainers.shaded.javax.inject.Inject;

@Testcontainers
@MicronautTest
public class MyTest{

    static final GenericContainer RABBITMQ_CONTAINER;

    static {
        RABBITMQ_CONTAINER = new GenericContainer<>("rabbitmq:3-management")
                .withExposedPorts(5672,15672)
                .withCreateContainerCmdModifier(cmd -> cmd.withHostName("my-rabbit"))
                .withCreateContainerCmdModifier(cmd -> cmd.withName("some-rabbit"));
        RABBITMQ_CONTAINER.start();
    }

    private static EmbeddedServer server;

    @Inject
    ProductClient productClient;

    @BeforeAll
    public static void setupServer() {
        Integer mappedPort = RABBITMQ_CONTAINER.getMappedPort(5672);
        System.out.println(RABBITMQ_CONTAINER.getMappedPort(15672));

        // using the random mapped testcontainers port for rabbitmq
        server = ApplicationContext.run(EmbeddedServer.class, PropertySource.of("test", CollectionUtils.mapOf(
                "rabbitmq.port", mappedPort
        )));

    }

    @AfterAll
    public static void stopServer() throws InterruptedException {
        if (server != null) {
            server.stop();
        }
    }

    @Test
    public void testHello() throws Exception {
        productClient.send("quickstart".getBytes());
        System.out.println();

    }
}
```

As you can see I tried to ramp up the container manually and via the @Testcontainer annotation (just for a test). The rabbitmq test container should start and after it started I need to invoke the getMappedPort() method to get the random port Testcontainers runs my rabbitmq container. This mapped port I need to insert into the MicronautTest configuration. This is not possible as I see it right now because you can only reference a yaml file. 
So my goal is it to start MicronautTest with a dynamic configuration (with the dynamically assigned random mapped container port)

This is how I did it without MicronautTest and JUnit 4
```
public class MyTest {

    @ClassRule
    public static GenericContainer rabbitMq = new GenericContainer<>("rabbitmq:3-management")
            .withExposedPorts(5672,15672)
            .withCreateContainerCmdModifier(cmd -> cmd.withHostName("my-rabbit"))
            .withCreateContainerCmdModifier(cmd -> cmd.withName("some-rabbit"));

    private static EmbeddedServer server;

    private static ProductClient productClient;

    @BeforeClass
    public static void setupServer() {
        Integer mappedPort = rabbitMq.getMappedPort(5672);
        System.out.println(rabbitMq.getMappedPort(15672));

        // using the random mapped testcontainers port for rabbitmq
        server = ApplicationContext.run(EmbeddedServer.class, PropertySource.of("test", CollectionUtils.mapOf(
                "rabbitmq.port", mappedPort
        )));
        productClient=  server.getApplicationContext().getBean(ProductClient.class);

    }

    @AfterClass
    public static void stopServer() throws InterruptedException {
        if (server != null) {
            server.stop();
        }
    }

    @Test
    public void testHello() throws Exception {
        productClient.send("quickstart".getBytes());
        System.out.println();

    }
}
```

**Comment by asarkar** [comment]
You can do this by manually starting and stopping the embedded server; See [this](https://github.com/asarkar/url-shortener/blob/master/src/test/kotlin/org/asarkar/urlshortener/ApplicationTest.kt) test class.

Currently, there are two limitations with micronaut-test that prevents using it for your use case:
1. Docker containers start independently by design, and if your app is not able to connect to a dependent container, like Cassandra for example, it will fail to start (assuming you're using Micronaut autoconfig).
2. There's no way to inject properties dynamically in the test context. See https://github.com/micronaut-projects/micronaut-test/issues/32.

**Comment by graemerocher** [comment]
I think this can be handled now with `@TestInstance(TestInstance.Lifecycle.PER_CLASS)` on the annotation. See https://github.com/micronaut-projects/micronaut-test/blob/master/test-junit5/src/test/java/io/micronaut/test/junit5/InjectSharedTest.java
