### ISSUE TITLE
@MicronautTest Annotation w Spock Not Inherited from Parent Class

### ISSUE THREAD

**Issue by brianwyka** [micronaut-projects/micronaut-test#27]
# Description
When using `@MicronautTest` in a spock specification hierarchy, the annotation is not inherited to concrete implementation specifications

## Version
Micronaut: `1.1.0.M1`
Micronaut Test: `1.0.2`

## Simple Example

```groovy
@MicronautTest
class ControllerSpecification extends Specification {
//share test logic and setup
}

class ControllerSpec extends ControllerSpecification {
// test code
}
```

## Workaround
Simply add `@MicronautTest` to `ControllerSpec`

**Comment by puneetbehl** [comment]
Duplicate #35
