### ISSUE TITLE
Eagerly Initialize Singletons With MicronautTest Annotation Tests

### ISSUE THREAD

**Issue by jeffbrown** [micronaut-projects/micronaut-test#277]
The context can be configured to eagerly initialize singletons using something like this...

```
Micronaut.build(args)
            .eagerInitSingletons(true) 
            .mainClass(Application.class).start()
```

It would be good to have the ability to eagerly initialize singletons in a test that uses `@MicronautTest`.

**Comment by cosmin-marginean** [comment]
+1

**Comment by graemerocher** [comment]
I think rather than this we should allow the test to implement an TestApplicationConextBuilder interface that includes a method that lets you return the builder. The annotation is going to get too complicated if we try to include every feature from the builder interface in it

**Comment by cosmin-marginean** [comment]
@graemerocher I agree. This was the broader point I made (eventually) when raising the question that produced this ticket, thanks to Jeff: https://stackoverflow.com/questions/63727162/best-practice-for-application-bootstrap-in-tests

**Comment by alvarosanchez** [comment]
I also agree with @graemerocher.

PRs are welcomed for this improvement.

**Comment by angelyan** [comment]
This can be done with the `contextBuilder` parameter:

```java
@MicronautTest(contextBuilder = CustomContextBuilder.class)
```

```java
public class CustomContextBuilder extends DefaultApplicationContextBuilder {

    public CustomContextBuilder() {
        eagerInitSingletons(true);
    }
}
```

**Comment by ttzn** [comment]
@graemerocher if I'm not mistaken, application context initialization is done in the `beforeAll()` callback to allow reuse, so making the test class implement an interface wouldn't really work (we'd need to instantiate the class outside the context of a test, which could surprise the user).

As @angelyan mentioned, there is already the possibility of providing a custom builder interface. I think this already covers the eager initialization use case pretty well. People who need advanced customization can always start their own contexts.

**Comment by graemerocher** [comment]
I agree this is more of a documentation issue
