### ISSUE TITLE
Unable to @MockBean(RxHttpClient)

### ISSUE THREAD

**Issue by winstaan74** [micronaut-projects/micronaut-test#29]
Hi.
I have a bean that uses a low-level RxHttpClient to call out to an external REST api (abridged below)

```groovy
interface NifiService {
    Flowable<Boolean> isTransformerWorkerRunning()
}
```

```groovy
@Singleton
class NifiServiceImpl implements NifiService {

    @Inject
    @Client('transformer-worker')
    RxHttpClient client

    Flowable<Boolean> isTransformerWorkerRunning() {
        client.retrieve(HttpRequest.GET("/nifi-api/flow/status")).map({ true }).onErrorReturnItem(false)
    }
```

I'm trying to write a unit test that stubs out `client` so I can test all the code branches without having access to the external api. (which seems a reasonable thing to do)

Here's my attempt - no matter what combination of annotations I use, the real client isn't replaced by the mock.

```groovy
@MicronautTest
class NifiServiceImplSpec extends Specification {

    @Inject
    NifiServiceImpl nifi

    @Inject
    @Client('transformer-worker')
    RxHttpClient client

    void 'status '() {
        when:
        def status = nifi.isTransformerWorkerRunning()

        then:
        1 * client.retrieve(_) >> Flowable.just('ok')
        status.blockingFirst() == true
    }

    @MockBean(RxHttpClient)
// various attempts at making the mock 'bite'
//    @Named('transformer-worker')
//    @Replaces(named='transformer-worker')
//    @Client('transformer-worker')
    RxHttpClient mockClient() {
        Mock(RxHttpClient)
    }
}
```
The test output for most annotation combinations is
```
Too few invocations for:

1 * client.retrieve(_) >> Flowable.just('ok')   (0 invocations)

Unmatched invocations (ordered by similarity):

None
```

Is this a known limitation, or is it something that could be clarified in the documentation?

**Comment by dcmoeller** [comment]
Just an idea: As far as I understand the `@MockBean` feature you have to address a `class` with this annotation, not an `interface` as you did with `@MockBean(RxHttpClient)`. So maybe you get it working with `@MockBean(DefaultHttpClient)`, cause this type implements the `RxHttpClient` interface.

**Comment by winstaan74** [comment]
Argh! yes. that works. 
Thank you - & Sorry for wasting your time.
Could I request that the javadoc on MockBean be extended to emphasize that .value must take the implementation class, not the interface.
