### ISSUE TITLE
Spock's fixture methods don't work when using @MicronautTest

### ISSUE THREAD

**Issue by Crow-EH** [micronaut-projects/micronaut-test#3]
Hi everyone,

I recently tried to use the new `@MicronautTest` annotation in my tests.
While it has been a breeze with Java/Junit5, using it in a Spock specification seems to prevent the fixture methods from triggering.

Is there any limitation that has not been documented ? Or is it a bug ?

**Comment by graemerocher** [comment]
Thanks will take a look

**Comment by graemerocher** [comment]
I release 1.0.0 RC2 to resolve this. Thanks for the report

**Comment by SJWooten** [comment]
I am still seeing problems with setup() and setupSpec() in RC2. When I included either fixture method, all of my @Inject'd beans and @Property's change to null. If you use the setup/given blocks, works fine.
