### ISSUE TITLE
How to run tests outside transaction?

### ISSUE THREAD

**Issue by SirWojtek** [micronaut-projects/micronaut-test#31]
Hey, I am running tests with `@MicronautTest` annotation using JPA and Hibernate to test transaction related fragment of implementation and after spending some time to figure out why it is not working I found that Micronaut tests are running inside own transaction:
```java
package example.micronaut;

import static org.junit.jupiter.api.Assertions.assertFalse;

import io.micronaut.test.annotation.MicronautTest;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.junit.jupiter.api.Test;

@MicronautTest
public class TransactionTest {

  @PersistenceContext
  EntityManager entityManager;

  @Test
  public void isInTransactionTest() {
    assertFalse(entityManager.getTransaction().isActive());  // FAILS
  }

}
```

Is there a handy way to disable that feature or at least change isolation level of that transaction?

### Environment
* System: Arch Linux
* Micronaut version: 1.1.0.RC1
* Micronaut Test JUnit version: 1.0.2
* JDK version: 1.8 (OpenJDK)

### Example
The example is available [here](https://github.com/SirWojtek/micronaut-data-access-jpa-hibernate), to reproduce the issue run `gradle test`.

**Comment by audathuynh** [comment]
Each test in `micronaut` is a transaction. 
Here is my way to have a non-transaction to tests my own transactions.
```
@MicronautTest
public class TransactionTest {
  @Inject
  TransactionTestHelper testHelper;
  @Test
  public void testTransaction() {
      testHelper.testTransaction();
  }
}
```

```
@Singleton
@Transactional(propagation = Propagation.NOT_SUPPORTED)
public class TransactionTestHelper {
    
    public void testTransaction() {
       // this method is not run in a transaction.
       // call transactions here
   }
}
```

**Comment by graemerocher** [comment]
We probably need a way to disable this. Thanks for the report

**Comment by SirWojtek** [comment]
Thank you for submitting the elegant solution @graemerocher. Cheers!
