### ISSUE TITLE
Using entity manager for integration test (Java/Junit5)

### ISSUE THREAD

**Issue by naspredam** [micronaut-projects/micronaut-test#314]
### Steps to Reproduce

1. Create http api service
2. Create integration test
3. Using Entity Manager to persist to a relation database

### Expected Behaviour

I can use EntityManager to persist some data to the database and then on calling the service should retrieve the entities persisted.

### Actual Behaviour

I have to do commit explicit, losing the capability to rollback at the end of the test.

### Environment Information

- **Operating System**: MacOS Catalina
- **Micronaut Version:** 2.1.1
- **JDK Version:** 14/15

### Example Application

I have create the endpoint GET to get all users and when I try to perform this integration test:

```
...
import io.micronaut.test.extensions.junit5.annotation.MicronautTest;
...

@MicronautTest
public class UserControllerTest {

    @Inject
    @Client("/")
    private RxHttpClient client;

    @Inject
    private EntityManager entityManager;

    @Test
    public void shouldReturnTheUserPersisted() {
        UserData frodoBaggingsUser = UserData.builder()
                .firstName("Frodo")
                .lastName("Baggins")
                .phone("+blah")
                .build();
        entityManager.persist(userData1);
        entityManager.persist(userData2);
//        entityManager.getTransaction().commit();

        List<UserData> usersResponse = client.toBlocking()
                .retrieve(GET("/users"), Argument.listOf(UserData.class));

        assertThat(usersResponse).hasSize(1)
            .containsExactlyInAnyOrder(frodoBaggingsUser);
    }
}
```

When I do not commit, the GET return empty... when I uncomment commit the test passes. However, when I commit the transaction, it is not able to rollback after the test... this I found out as, I did another test where GET returns empty when no data is present on the database... but! when I execute this first, the transaction returns the two users... not the expected empty list, alone the empty test case passes. So we have a coupling between tests, as the transaction is not able to undo a the commit.

When I use the commit, I need to add on the empty test scenario to clean up the using entityManager removing all users...

This is something that on spring works with no need to commit anything.

**Comment by graemerocher** [comment]
Micronaut configures transaction rollback for each test method by default, if you want to manage this yourself you can do:

```
@MicronautTest(transactional=false)
```

To disable transaction management, however you will need to wrap your write operations in your own transaction.

**Comment by naspredam** [comment]
Thanks for this fast reply, however I really do not want to manager the transaction by myself...

I am able to do on spring-boot:
- do inserts to the database via EntityManager
- call the endpoint
- check that the results are the same that I inserted via EntityManager
- after the test the rollback on spring works like charm. No other tests knows what I did on a specific test with EntityManager

However here, I am forced to commit the changes... then the rollback does not do anything! As the transaction is already committed...

So the answer that I am looking for is:

Why do I have to commit????
Why on doing the persistence on the entity manager (which is under the test transaction test) it is not reflected on the retrieve via endpoint?

It seems that, even I am under a test transaction (that rollbacks everything and so on) what is not able is to have a single transaction, so, what I understand is:

- When I am using the entityManager this is stored on a transaction
- When I am using the `client.toBlocking().retrieve("GET")...` this is executed on a different transaction, this is why the retrieve returns empty, it is not able to see what I did on the first transaction, unless I commit...

I did see this option:

```
@MicronautTest(transactional=false)
```

However this is not what I meant to...

**Comment by graemerocher** [comment]
The reason is because the client request happens in a different thread from your test execution thread. The test execution thread has an active transaction and by the rules of transaction visibility logic that is happening in a completely different thread (ie your client request to the server) cannot do dirty reads on an in process transaction

If you did the same thing in Spring (ie wrapped the test in transaction rollback and then send a request to the server via an HTTP client) you would see exactly the same behaviour

**Comment by naspredam** [comment]
Thanks again for your fast reply.

I got a little intrigued with your response.

These kind of tests, I did so many times over the past years. Due to your affirmation, I did it again, for the same example. And, I was able to do it, with no much effort with spring-boot... here is the test, passing with no commit:

```
...

@SpringBootTest
@AutoConfigureMockMvc
@Transactional
public class UserControllerIntegrationTest {

    @Autowired
    private MockMvc mvc;

    @Autowired
    private EntityManager entityManager;

    @Test
    public void shouldReturnNonEmptyUserList_WhenUserArePersisted() throws Exception {
        UserData frodoBaggingsUser = UserData.builder()
                .firstName("Frodo")
                .lastName("Baggins")
                .phone("+blah")
                .build();
        entityManager.persist(frodoBaggingsUser);

        mvc.perform(get("/users"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$", hasSize(1)))
                .andExpect(jsonPath("[0].id", is(1)))
                .andExpect(jsonPath("[0].first_name", is("Frodo")))
                .andExpect(jsonPath("[0].last_name", is("Baggins")))
                .andExpect(jsonPath("[0].phone", is("+blah")));
    }

}
```

Here there is the test class for more details (if you would like):
https://github.com/naspredam/rest-spring-boot-java-users/blob/main/src/test/java/com/service/rest/users/UserControllerIntegrationTest.java#L40-L55

There is more annotations to be written, but it is able to guarantee that only one transaction is open per test. After the test it rolls back any DML (and really rollbacking as I did not need to commit anything). The limitation to keep in mind is: it does not reset sequences and auto-increment columns, as this would be not only rollback, but also applying DLLs.

With this, I can use the EntityManager to populate the data (given), and then call the endpoint to validate that the response is what supposes to be. Spring-boot uses MockMvc, not sure if this makes all the magic keeping all on the same transition...

Then, it is something to keep in mind that `@MicronautTest` does not guarantee a single transaction test scope. This makes me thing that for integration test maybe you will always need to manually handle the transaction.

Thanks again for your fast responses.

**Comment by graemerocher** [comment]
Mock MVC is not the same as the Micronaut client which sends an actual HTTP request. If you inject the controller and invoke your get users method directly you will see the same behaviour
