### ISSUE TITLE
Support dynamically injecting properties in the test context

### ISSUE THREAD

**Issue by asarkar** [micronaut-projects/micronaut-test#32]
Many integration tests require spinning up dependent services, like a mock server, or an in-memory database. To avoid port conflicts, and hence the test failing randomly, it is highly recommended to start these services on any available port. Obviously, the application needs to be told about these ports, which means the test framework has to provide a way to inject properties dynamically before the tests are run.
Spring allows for this using `ApplicationContextInitializer`, which can be specified on a test class as follows: `@ContextConfiguration(initializers = MyTestContextInitializer.class)`.

This ticket is for `@MicronautTest` to support such feature.

**Comment by graemerocher** [comment]
Yeah we need to resolve this. I think what we should do is add support for declaring:

```
@PropertySource
static Map<String,Object> props = Collections.singletonMap("my.port", myContainer.getPort())
```

**Comment by asarkar** [comment]
@graemerocher I'm not sure I understand your proposal. The port resolution must be deferred until the dependent service actually starts. When would the `@PropertySource` annotation be evaluated? I thought Micronaut aims to process annotations at compile time.

**Comment by graemerocher** [comment]
Micronaut resolves properties are runtime, it has to adapt to where it runs so doing so at compilation time would not make sense

**Comment by abedurftig** [comment]
Would this also apply to the scenario where I have two service implementations wit the `@Requires` annotation like this?

```
@Requires(property = "myorg.service.email", value = "provider-x")
class ProviderXEmailService : EmailService {}

@Requires(property = "myorg.service.email", value = "provider-y")
class ProviderYEmailService : EmailService {}
```
There is no service without an annotation. If I want to write an integration test I need to be able to make sure a service gets injected into the controller, right?

**Comment by graemerocher** [comment]
@abedurftig that is already possibly by using `@Property` on your test

```
@Property(name = "myorg.service.email", value = "provider-x")
@MicronautTest
class MyTest {}
```

**Comment by graemerocher** [comment]
In the end implemented this with a `TestPropertyProvider` interface

**Comment by asarkar** [comment]
@graemerocher Please show an example usage of `TestPropertyProvider`.

**Comment by graemerocher** [comment]
You can see an example for JUnit in the linked commit https://github.com/micronaut-projects/micronaut-test/commit/0f32d13876decfc33f3f94238e280552422bf170#diff-985f52f80183621fbb0bc4f031044158R16

The feature requires `@TestInstance(TestInstance.Lifecycle.PER_CLASS)`

**Comment by asarkar** [comment]
@graemerocher
Perhaps an annotation `TestPropertyProvider` with attributes `classes`, `inline` and `resources` would be more flexible. `classes` would have a single `public` method returning `Map<String, Object>`, `inline` a list of key values, and `resources` YAML and/or property files. Any number of these attributes could be combined.

**Comment by graemerocher** [comment]
annotations don't allow for a programmatic approach. Also it would have to be a type level annotation and for that we already have https://github.com/micronaut-projects/micronaut-test/blob/master/test-junit5/src/test/java/io/micronaut/test/junit5/PropertySourceTest.java#L8

**Comment by asarkar** [comment]
> annotations don't allow for a programmatic approach

In my proposal, it does.
> classes would have a single public method returning Map<String, Object>

Instead of multiple ways of providing property values, I'm suggesting having a single annotation that allows for multiple sources. Heck, it doesn't even need to be `TestPropertyProvider`, it could just as well be `PropertyProvider` and used in main code.

For example:
```
@PropertyProvider(classes = {Foo.class}, inline = {"foo=bar", "a=b"}, resources={"foo.yaml", "bar.yaml"}
public class Foo {
  public Map<String, Object> props() {...}
}
```

**Comment by graemerocher** [comment]
Seems reasonable although `inline` is duplicated by 

```java
@Property(name="foo", value="bar")
```

And `resources` is duplicated by 

```java
@MicronautTest(propertySources="foo.yaml")
```

So the only thing that is adding anything new is `classes`, although I see the value in unifying the different approaches to one annotation

**Comment by asarkar** [comment]
> value in unifying the different approaches

Exactly. IMO, Spring went off the rails with hundreds of annotations.

**Comment by alexwilbur** [comment]
I like @asarkar 's suggestion. Did anything ever come of this unifying annotation?

**Comment by mateuszwlosek** [comment]
Why was that issue closed? As Spring Boot allows this feature it's difficult to migrate to Micronaut without the functionality.

**Comment by abedurftig** [comment]
> Why was that issue closed? As Spring Boot allows this feature it's difficult to migrate to Micronaut without the functionality.

Your test class should implement TestPropertiesProvider. Is that what your are looking for?

**Comment by valepakh** [comment]
> > Why was that issue closed? As Spring Boot allows this feature it's difficult to migrate to Micronaut without the functionality.
> 
> Your test class should implement TestPropertiesProvider. Is that what your are looking for?

I wonder why the `TestPropertiesProvider` allows only `String` property values? I needed to set the property value for Micronaut which is of `java.util.Map` type and it seems my only option is to create a properties file?
Actually it seems that even the properties file wouldn't help if I want to set the `jackson.deserialization` property, which is actually of the type `Map<DeserializationFeature, Boolean>`

EDIT: Anyhow, if anyone stumbles upon this in search of the solution, it's quite easy, just put a dot after the property name and add a key: `@Property(name = "jackson.deserialization.USE_BIG_DECIMAL_FOR_FLOATS", value = "true")`

**Comment by r1m** [comment]
> Your test class should implement TestPropertiesProvider. Is that what your are looking for?

This is something, but this is called during the beforeAll of the MicronautExtension. So values must be initialized at this point, which is not always possible.

What would be a working version of this ?

```java
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
@MicronautTest()
class ControllerTest {
    
    @RegisterExtension
    static WireMockExtension wMock =
            WireMockExtension.newInstance().options(wireMockConfig().dynamicPort()).build();
   
    @Override
    public @NonNull Map<String, String> getProperties() {
       return Collections
                .singletonMap("micronaut.http.services.my.url", wMock.baseUrl()); // how to get the value in time ?
    }
}
```

**Comment by chase-miller** [comment]
This appears to still be a problem (see @r1m's [post](https://github.com/micronaut-projects/micronaut-test/issues/32#issuecomment-2609892479) above), yet this issue is closed. @graemerocher will you please re-open this issue?

**Comment by graemerocher** [comment]
perhaps create a separate issue with @r1m's query, this ticket has already gone off the rails and become too convoluted
