### ISSUE TITLE
NoSuchBeanException whem using @MicronautTest in a Java 11 modular application with JUnit 5

### ISSUE THREAD

**Issue by weiqigao** [micronaut-projects/micronaut-test#33]
I'm trying to use Micronaut Test in a Java 11 modular application built with Gradle 5.4 with the [Gradle module plugin](https://github.com/java9-modularity/gradle-modules-plugin), tested with JUnit 5.  And I'm encountering a
```
io.micronaut.context.exceptions.DependencyInjectionException:
    Failed to inject value for field [foo] of class: foo.FooTest
```
caused by
```
io.micronaut.context.exceptions.NoSuchBeanException:
    No bean of type [foo.Foo] exists. Ensure the class is declared a bean
    and if you are using Java or Kotlin make sure you have enabled
    annotation processing.
```
I have created a simple test case [micronaut-test-modules-issue](https://github.com/weiqigao/micronaut-test-modules-issue)

The root cause seems to be when running tests in Gradle module plugin, the compilation and annotation processing results in the
```
    build/classes/java/main
    build/classes/java/test
```
directories have to be put into the same module (because they contain the same packages) through a `--patch-module` command line argument similar to the following:
```
--patch-module micronaut.test.modules.issue=build/classes/java/test
```
while the `build/classes/java/main` was already put on the module path.  And in doing so the copy of the
```
    META-INF/services/io.micronaut.inject.BeanDefinitionReference
```
file in the `build/classes/java/test` directory shadows the one in the `build/classes/java/main`.

**Comment by weiqigao** [comment]
I realize this night not be a bug in Micronaut Test, just the interaction between Micronaut Test with the Gradle module plugin.

And here is my hacky work around for this issue:
```
test {
    useJUnitPlatform()
    testLogging {
        events 'passed', 'skipped', 'failed'
    }
    doFirst {
        def refFileName = "/META-INF/services/io.micronaut.inject.BeanDefinitionReference"
        def mainRefFile = file("$buildDir/classes/java/main" + refFileName)
        def testRefFile = file("$buildDir/classes/java/test" + refFileName)
        def mainRefFileText = mainRefFile.getText()
        def testRefFileText = testRefFile.getText()
        if (!testRefFileText.contains(mainRefFileText)) {
            testRefFileText = mainRefFileText + testRefFileText
        }
        testRefFile.setText(testRefFileText)
    }
}
```
It does the obvious, and the test does run successfully afterwards.  It would be ideal if this action can be improved and incorporated into some Gradle plugin.  But I don't know which one it should belong.

**Comment by Kyu** [comment]
Your workaround is great, I was making my beans static all over the place because of this. I hope this is somehow resolved in the actual repo.
