### ISSUE TITLE
@MockBean named does nothing

### ISSUE THREAD

**Issue by fabienrenaud** [micronaut-projects/micronaut-test#331]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Provide a `@Named` `Singleton` bean implementing a core java functional interface:
```
  @Singleton
  @Named("my-str-supplier")
  Supplier<String> myStrSupplier() {
    return () -> "foo";
  }
```
2. Implement a controller using the bean
3. Write a test and try mocking the singleton bean solely with `@MockBean`:
```
  @MockBean(named = "my-str-supplier")
  Supplier<String> supplier() {
    return () -> "bar";
  }
```
or
```
  @MockBean(bean = Supplier.class, named = "my-str-supplier")
  Supplier<String> supplier() {
    return () -> "bar";
  }
```
Neither work.

### Expected Behaviour

In the example above,
```
  @MockBean(named = "my-str-supplier")
  Supplier<String> supplier() {
    return () -> "bar";
  }
```
should suffice to mock the singleton bean.
At the very least, this should work:
```
  @MockBean(bean = Supplier.class, named = "my-str-supplier")
  Supplier<String> supplier() {
    return () -> "bar";
  }
```
although providing the bean class name should not be necessary here and has little value since  the generic type is not defined.

### Actual Behaviour

Using:
```
@MockBean(bean = Supplier.class, named = "my-str-supplier")
```
Gives:
```
bug.micronaut.AppTest > test_bug() FAILED
    io.micronaut.http.client.exceptions.HttpClientResponseException: Internal Server Error: Failed to inject value for parameter [supplier] of class: bug.micronaut.App$Control

    Message: No bean of type [java.util.function.Supplier] exists for the given qualifier: @Named('my-str-supplier'). Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
    Path Taken: new Control([Supplier supplier])
```

And using:
```
@MockBean(named = "my-str-supplier")
```
does mock not the bean (bean from main source is used).

I have to define both the class in `@MockBean` and use the `@Named` annotation in tests:
```
@Named("my-str-supplier")
@MockBean(Supplier.class)
```

### Environment Information

- **Operating System**: Mac Os Mojave (10.14.6)
- **Micronaut Version:** 1.2.6
- **JDK Version:** Oracle JDK 11.0.2

### Example Application

See: https://github.com/fabienrenaud/micronaut-bug-mockbean-named
See App.java and AppTest.java

Notes:
 * `@MockBean`'s `named` field is not documented in https://micronaut-projects.github.io/micronaut-test/latest/guide/index.html it's javadoc just says "The name of the bean to replace in the case of multiple beans."
 * In further attempts to add a 2nd supplier<string> to the main source (with a different name), I was completely unable to get my test working with 1 or 2 mockbeans (tried several combinations of @MockBean(Supplier.class, named=) and `@Named` and could only get them to pass after removing all MockBean.
    ```
      @Singleton  @Named("my-str-supplier") Supplier<String> myStrSupplier2() { return () -> "foo"; }
      @Singleton  @Named("my-str-supplier-2") Supplier<String> myStrSupplier2() { return () -> "bar"; }
    ```

**Comment by graemerocher** [comment]
Got to the bottom of this and needs a new release of Micronaut core (2.2.1)
