### ISSUE TITLE
Missing repositories in build.gradle

### ISSUE THREAD

**Issue by sdedic** [micronaut-projects/micronaut-test#396]
### Task List

- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

1. `git clone git@github.com:micronaut-projects/micronaut-test.git`
2. run `./gradlew dependencies` on the `micronaut-test` root project

IDE steps to reproduce:
1. `git clone git@github.com:micronaut-projects/micronaut-test.git`
2. use NetBeans IDE 12.3 (or 12.2.), see http://netbeans.apache.org/download/index.html
3. Use `File | Open project` and open `micronaut-test`
4. Confirm possible download (required for java support)
5. After project opens, a dialog pops up "Project has problems". Review problems (jansi:1.14 unavailable)

### Expected Behaviour

Dependencies should be printed, like
```
documentation
\--- org.fusesource.jansi:jansi:1.14
```

### Actual Behaviour

Failed dependency is printed:
```
documentation
\--- org.fusesource.jansi:jansi:1.14 FAILED
```
### Environment Information

- **Operating System**: Linux Ubuntu 19.04
- **Micronaut Version:** github master
- **JDK Version:** Oracle JDK 8

### Full description
The NetBeans IDE detects a failed dependency, so it marks the project as broken.

The same happens when I executed `./gradlew dependencies` from the commandline on pristine git checkout of the `micronaut-test` project, so I suppose the project is missing some configuration. It seems this is caused by a missing `repositories` for regular (non-plugin) artifacts. 

I suggest to add
```
repositories {
   maven { url "https://repo.grails.org/grails/core" }
}
```
that repository is used by `micronaut-build`, `micronaut-core` projects as well.

**Comment by JaroslavTulach** [comment]
I can confirm I see the same problem when using this revision:
```
micronaut-test$ git log | head -n 5
commit e3a6225a3b98923f9bba865e434ea3eb896fa3f2
Author: micronaut-build <65172877+micronaut-build@users.noreply.github.com>
Date:   Mon Mar 1 04:28:18 2021 -0600

    [test] Update common files for branch master (#391)
```

**Comment by graemerocher** [comment]
Fixed by https://github.com/micronaut-projects/micronaut-test/commit/d5f9c200d941b0eaa9171cc3b5ce688f0146c666
