### ISSUE TITLE
Created beans with @MockBean not injected correctly in other beans

### ISSUE THREAD

**Issue by danielplappert** [micronaut-projects/micronaut-test#41]
When @MockBean is used the created mock is not (re-)injected correctly in other beans. 

I have a controller using a service:

```
@Controller
public class HelloWorldController {
    private final AcmeService acmeService;

    @Inject
    public HelloWorldController(AcmeService acmeService) {
        this.acmeService = acmeService;
    }

    @Get("/")
    public String handle() {
        acmeServicel.doSomething("test");

        return "Hello World";
    }
}
```

To simulated different use cases I created the following test:

```
@MicronautTest
public class HelloWorldControllerTest {

   @Inject
   private AcmeService acmeService;
   @Inject
   @Client("/")
   private RxHttpClient client;

   @MockBean(AcmeService.class)
   public AcmeService acmeService() {
      return Mockito.mock(AcmeService.class);
   }

   @Test
   public void test_without_exception() {

      HttpResponse httpResponse = client.toBlocking().exchange(HttpRequest.GET("/"));
      Assertions.assertEquals(HttpStatus.OK, httpResponse.getStatus());
   }

   @Test
   public void test_with_nullpointer_exception() {

      Mockito.doThrow(new NullPointerException("nullpointer"))
            .when(acmeService)
            .doSomething(Mockito.anyString());

      HttpClientResponseException responseException = Assertions.assertThrows(HttpClientResponseException.class,
            () -> client.toBlocking().exchange(HttpRequest.GET("/")));
   }

}
```

The second test fails because no exception is thrown. 

Debugging the test shows that the method annotated with @MockBean is executed before each test. But only in the first test (test_without_exception) the mocked AcmeService is identical with the AcmeService used by the HelloWorldController. 
In the second test (test_with_nullpointer_exception) the mocked AcmeService within the test is now different (because a new mock is created) from the one used by the controller. The AcmeService used by the controller is still the one used during the first test. 

According to your [doc](https://micronaut-projects.github.io/micronaut-test/latest/guide/index.html): "[...] the controller will have a proxy that points to the Mock(..) instance injected. For each iteration of the test the mock is refreshed". This is true but the problem is that the refreshed mock is not used by the controller.

**Comment by graemerocher** [comment]
You are injecting `AcmeServiceImpl` into the controller and not `AcmeService`

**Comment by danielplappert** [comment]
@graemerocher: sorry, was a copy-and-paste error. I corrected the above controller example.

**Comment by graemerocher** [comment]
Might be related to https://github.com/micronaut-projects/micronaut-test/issues/39

**Comment by puneetbehl** [comment]
It seems to working fine with Micronaut v1.1.3 please see the following attached sample:

- [hello-junit.zip](https://github.com/micronaut-projects/micronaut-test/files/3265309/hello-junit.zip)

**Comment by danielplappert** [comment]
@graemerocher: Thanks for fixing. It's now working with v1.1.3.

**Comment by mzouitni** [comment]
I am seeing the same issue still pop up in 1.1.3
