### ISSUE TITLE
MockBean in Spock test is broken since Micronaut 1.1.3

### ISSUE THREAD

**Issue by saw303** [micronaut-projects/micronaut-test#46]
Since Micronaut 1.1.3 the bean replacement by using `@MockBean` does not work reliable anymore.

Given the following [Spock](https://github.com/saw303/micronaut-spock-mock-bug/blob/master/src/test/groovy/micronaut/spock/mock/bug/ReplaceBeanBugSpec.groovy#L21) test you find the following test configuration 

```groovy
@MicronautTest
class ReplaceBeanBugSpec extends Specification {

    @Inject
    @Subject
    AnotherService anotherService

    @Inject
    SuperService superService

    @MockBean(SuperService)
    SuperService superService() {
        Mock(SuperService)
    }
    // test code omitted ... (see below or in link)
}
```

and two test cases:

- [first test works](https://github.com/saw303/micronaut-spock-mock-bug/blob/master/src/test/groovy/micronaut/spock/mock/bug/ReplaceBeanBugSpec.groovy#L35)

```groovy
void "first test works"() {

        when:
        anotherService.greet("Silvio")

        then:
        1 * superService.hello("Silvio") >> "Good day Silvio"
        0 * _
}
```

- [second test works](https://github.com/saw303/micronaut-spock-mock-bug/blob/master/src/test/groovy/micronaut/spock/mock/bug/ReplaceBeanBugSpec.groovy#L45)

```groovy
void "second test works"() {

        when:
        anotherService.greet("Angela")

        then:
        1 * superService.hello("Angela") >> "Good day Angela"
        0 * _
}
```

This test specification demonstrates a bug introduced in Micronaut 1.1.3. When replacing a bean with a Spock test the mock only works in the first test as expected.

**Actual behaviour**
When running the whole test suite -> test 1 is ok, test 2 fails
When running each test independently -> both are ok (independently)

**Expected behaviour**
When running the whole test suite -> test 1 & 2 are ok as it was in Micronaut 1.1.2

Please find a **sample application** in this [repository](https://github.com/saw303/micronaut-spock-mock-bug).

**Comment by graemerocher** [comment]
The test suite actually fails for me in 1.1.2 with

```
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [superService] of class: micronaut.spock.mock.bug.AnotherService

Message: Multiple possible bean candidates found: [micronaut.spock.mock.bug.$ReplaceBeanBugSpec$SuperServiceDefinition$Intercepted, micronaut.spock.mock.bug.SuperServiceImpl]
Path Taken: ReplaceBeanBugSpec.setAnotherService([AnotherService anotherService]) --> new AnotherService([SuperService superService])

```

**Comment by graemerocher** [comment]
The issue can be resolved simply by changing `@MockBean(SuperService)` to `@MockBean(SuperServiceImpl)`

Relates to this commit https://github.com/micronaut-projects/micronaut-core/commit/f1f06ad048e5bb063218bb43944896cecf033120
