### ISSUE TITLE
`@Inject` on test class constructor

### ISSUE THREAD

**Issue by binkley** [micronaut-projects/micronaut-test#48]
I'd like to reuse an idiom from Java Spring+Lombok when using JUnit 5:
```
@RequiredArgsConstructor(onConstructor = @__(@Autowired))
@SpringBootTest
class SomeTest {
    private final Foo foo;

    // my tests
}
```
I tried the same with `@MicronautTest` and `@Inject` without success.  The only option seemed to be field injection, rather than constructor injection.  For code hygiene, my team prefers final fields and ctor injection, when possible.

Reading the Micronaut 1.2 RC documentation, this seems supported for beans, so I'm guessing there is something in `@MicronautTest` which prevents this from working.

Is there a trick I'm missing?

FYI -- We've been exploring Micronaut as a replacement for Spring Boot.  Wonderful project!

**Comment by graemerocher** [comment]
Constructor injection is not yet supported in MicronautTest but should be technically possible I will investigate what can be done. Thanks for the feedback
