### ISSUE TITLE
Project with multiple test classes annotated with @MicronautTest invokes only one test class

### ISSUE THREAD

**Issue by alexwilbur** [micronaut-projects/micronaut-test#49]
If I define multiple test classes, each annotated with @MicronautTest, then I see only that surefire runs only the test cases of one class, even if multiple test classes are defined.  I discovered this in my own project, but it's reproducible with just the hello-world-java example. I'm guessing its something to do with the interplay between MicronautTest extension and JUnit..

How to reproduce:

1. Check out https://github.com/micronaut-projects/micronaut-examples/tree/master/hello-world-java locally, so using whatever the versions & dependencies are for this example project.

2. Copy and paste this class:
https://github.com/micronaut-projects/micronaut-examples/blob/master/hello-world-java/src/test/java/example/HelloControllerTest.java
... & call it something like HelloControllerTest2.java

Be sure to leave it inside the same package.

3. Edit the new file, https://github.com/micronaut-projects/micronaut-examples/blob/master/hello-world-java/src/test/java/example/HelloControllerTest2.java
... so that it simply calls Assertions.fail() from within the @Test annotated method.

4. from the command line, in the project root, run:

mvn clean test

Expected Behavior:
- both test cases are executed
- HelloControllerTest2.testHello() fails due to Assertions.fail()

Actual Behavior:
- HelloController2.testHello() is never invoked

Actual Output:
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running example.HelloControllerTest
09:16:17.577 [main] INFO  i.m.context.env.DefaultEnvironment - Established active environments: [test]
09:16:19.300 [nioEventLoopGroup-1-4] WARN  i.m.validation.ValidatingInterceptor - Beans requiring validation present, but no implementation of javax.validation configuration. Add an implementation (such as hibernate-validator) to prevent this error.
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.116 s - in example.HelloControllerTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO] 

If I run the tests via my IDE (which happens to be IntelliJ) then I see the expected bahavior.

**Comment by graemerocher** [comment]
What version? A similar issue was reported and resolved here https://github.com/micronaut-projects/micronaut-test/issues/13

**Comment by alexwilbur** [comment]
Looks like v1.1.0 https://github.com/micronaut-projects/micronaut-examples/blob/master/hello-world-java/pom.xml 

... but I see this with v1.1.3 too.

**Comment by graemerocher** [comment]
The import thing is the version of the `micronaut-test` dependency. You need 1.0.2 or above

**Comment by alexwilbur** [comment]
I think the example app uses 1.1.0 of MN-core, which equates to 1.0.2 of MN-test...

If I chase through the BOM version (of 1.1.0) in my IDE, I see:

https://github.com/micronaut-projects/micronaut-examples/blob/master/hello-world-java/pom.xml#L78

=> 

    <micronaut.test.version>1.0.2</micronaut.test.version>

**Comment by alexwilbur** [comment]
... and looking at the code, I definitely have that prior fix.

**Comment by graemerocher** [comment]
Oke will take a look. Thanks

**Comment by alexwilbur** [comment]
This is me being an idiot. Of course the test class name has to end in Test. Sigh.
