### ISSUE TITLE
Can't @MockBean an abstract class which declares an interface method it implements as final

### ISSUE THREAD

**Issue by casadogg** [micronaut-projects/micronaut-test#50]
**Setup**
- Micronaut v1.1.3
- Micronaut-GRPC  v1.0.1
- Micronaut-Test v1.0.5
- Kotlin v1.3.11
- Grpc v1.21.0 (netty-shaded, protobuf, services, stub)

**Context**

I have a gRPC service which I want to spy on. Every generated service (by protobuf compiler) has a class representing the service and an inner abstract class that implements an interface called `BindableService`.

Let's suppose I have a proto service called `AddressService`.

The following code would be generated:

```java
public final class AddressServiceGrpc {

  // bunch of stuff...

  public static abstract class AddressServiceImplBase implements BindableService {
    @Override public final ServerServiceDefinition bindService() { /*do stuff*/ }
  }
}
```

In my code I have:

```kotlin
open class AddressService : AddressServiceGrpc.AddressServiceImplBase() {
  // do stuff...
  // I want to verify if this method was called
  fun doSomething() {}
}
```

In my test I have:

```kotlin
@MockBean(AddressService::class)
fun addressService(): AddressServiceGrpc.AddressServiceImplBase {
  return spy { AddressService() }
}
```

I'm getting the following exception when running the `AddressServiceTest` (which is properly annotated with `@MicronautTest`):

```
io.micronaut.context.exceptions.BeanContextException
Unexpected error loading bean definition [com.xyz.$$AddressServiceTest$AddressServiceDefinition$InterceptedDefinition]: class com.xyz.$AddressServiceTest$AddressServiceDefinition$Intercepted overrides final method bindService.()Lio/grpc/ServerServiceDefinition;
```

Is there a way to do what I want? Or is it feasible to modify micronaut-test and add this possibility?
Please, let me know if you need more details.

**Comment by briankramer17** [comment]
I'm seeing the same thing when extending from Abstract tests that have @MockBean. (Using maven and junit5 and pure java if that's useful). As a work around, I'm just copying the @MockBean methods to each test

**Comment by graemerocher** [comment]
Can you try a newer version of Micronaut like 1.2.5? There were some problems with accidently overriding final methods that were fixed
