### ISSUE TITLE
Kotest 5.x.x support

### ISSUE THREAD

**Issue by glockbender** [micronaut-projects/micronaut-test#508]
### Issue description

Currently the plugin supports only 4.x.x kotest versions. Please provide support for kotest 5.x.x. See [changelog](https://kotest.io/docs/changelog.html) for more info.

**Comment by Nandi** [comment]
I would like to assist with this issue. What is the desired approach here:
1. Update the kotest module inplace, causing breaking changes and no longer supporting Kotest verrsion before 5.x
2. Create a new module for Kotest 5.x+

**Comment by Nandi** [comment]
I have made a PR here #531
