### ISSUE TITLE
Documentation examples are Broken on micronaut-projects.github.io

### ISSUE THREAD

**Issue by jxc876** [micronaut-projects/micronaut-test#509]
### Expected Behavior

Documentation examples on  [micronaut-projects.github.io](https://micronaut-projects.github.io/) should display code, ex:

```
{

    @MockBean(MathServiceImpl::class) // <1>
    fun mathService(): MathService {
        return mockk() // <2>
    }
}
```

### Actual Behaviour

Examples show this error: 

```
Unresolved directive in <stdin> - include::{kotlintesttests}/MathMockServiceTest.kt[]
```

![image](https://user-images.githubusercontent.com/5241849/151635036-4644c9a5-8130-4bef-bde2-ddc69fa0fd88.png)

### Steps To Reproduce

1. Go to https://micronaut-projects.github.io/micronaut-test/latest/guide/
2. Look at the code examples, they have "Unresolved directive"

### Version

Latest/guide

**Comment by sdelamo** [comment]
@timyates please look into this.
