### ISSUE TITLE
Embedded server doesn't show errors if it fails to start

### ISSUE THREAD

**Issue by asarkar** [micronaut-projects/micronaut-test#52]
JDK: OpenJDK 64-Bit Server VM Zulu11.31+11-CA (build 11.0.3+7-LTS, mixed mode)
Micronaut: 1.2.0.RC1
Micronaut test: 1.1.0.RC1
Kotlin: 1.3.41
JUnit: 5.5.0
IntelliJ: 2019.1.3
Kotlin plugin: 1.3.41

```
@Inject
private lateinit var server: EmbeddedServer
```

If the server fails to start, ti doesn't log any warnings or errors.

**Comment by alvarosanchez** [comment]
Can you upload a sample application that reproduces the issue?
