### ISSUE TITLE
Created beans with @MockBean not injected correctly in other beans

### ISSUE THREAD

**Issue by swarren-sumglobal** [micronaut-projects/micronaut-test#53]
Closed issue #41 [https://github.com/micronaut-projects/micronaut-test/issues/41] still occurs in 1.1.3 and 1.1.4. The application context has the newly created mock beans for each test. They're getting "re-"injected into the test, but they're not getting "re-"injected into other classes (e.g. Controller)

**Comment by paulolieuthier** [comment]
I'm also facing this. Is there a workaround?

**Comment by wombat9000** [comment]
I'm new to the framework, and I am also having trouble with this.

I observed some unintuitive behaviour, which I believe to be related to this issue:

    @Inject
    FirebaseTokenValidator tokenValidator;
    @Inject
    @Client("/")
    RxHttpClient client;

    @Test
    public void testHello() {
        when(tokenValidator.validateToken(any())).thenReturn(Flowable.just(new DefaultAuthentication("user", new HashMap<>())));
        assertEquals("Hello John", client.retrieve(HttpRequest.GET("/hello/John").bearerAuth("someToken"), Greeting.class).blockingFirst().getMessage());
    }

    @MockBean(FirebaseTokenValidator.class)
    FirebaseTokenValidator validator() {
        return mock(FirebaseTokenValidator.class);
    }

In this example, the `when(...)` appears to have no effect, the test fails with 
`Unexpected error occurred: publisher is null
java.lang.NullPointerException: publisher is null`. Same result as when I remove the statement alltogether.

However, when I move the `when(...)` into the mockSetup like so:

    @MockBean(FirebaseTokenValidator.class)
    FirebaseTokenValidator validator() {
        FirebaseTokenValidator mock = mock(FirebaseTokenValidator.class);
        when(mock.validateToken(any())).thenReturn(Flowable.just(new DefaultAuthentication("user", new HashMap<>())));
        return mock;
    }

it works, and the test passes. Naturally, this isn't very helpful as this doesn't allow to change the mock behaviour between test cases. This made me believe that the Bean injected into the test is different than the one used in the rest of the application.

Logging to console confirms:
`mockSetup: Mock for FirebaseTokenValidator, hashCode: 1381385045`
`test: Mock for FirebaseTokenValidator, hashCode: 1381385045`
`mockSetup: Mock for FirebaseTokenValidator, hashCode: 117681647`

Apparantly, the mockSetup gets run an additional time, replacing the mocked Bean with a new mock before the test has time to run.

**Workaround**: Make the mock static, and use the static reference throughout:
 
    static FirebaseTokenValidator validatorMock;
    
    @BeforeAll
    static void setUp() {
        validatorMock = mock(FirebaseTokenValidator.class);
    }

    @Test
    public void testHello() {
        when(tokenValidator.validateToken(any())).thenReturn(Flowable.just(new DefaultAuthentication("user", new HashMap<>())));
        assertEquals("Hello John", client.retrieve(HttpRequest.GET("/hello/John").bearerAuth("someToken"), Greeting.class).blockingFirst().getMessage());
    }

    @MockBean(FirebaseTokenValidator.class)
    FirebaseTokenValidator validator() {
        return validatorMock;
    }

**Comment by jameskleeh** [comment]
Please upload a sample application with steps to reproduce

**Comment by jedrzejserwa** [comment]
I had a similar case where I wanted to integration test Micronaut Rabbit Consumer with another dependency that was injected. My workaround was to create a separate [ApplicationContext](https://docs.micronaut.io/latest/api/io/micronaut/context/ApplicationContext.html) where mocked dependency was registered via [Micronaut API docs (https://docs.micronaut.io/latest/api/io/micronaut/context/ApplicationContext.html#registerSingleton-java.lang.Class-T-io.micronaut.context.Qualifier-) method as Micronaut bean. Then, after the context is created, you can refer to the mock as always you would
