### ISSUE TITLE
JUnit5 test both commits and rolls back transaction

### ISSUE THREAD

**Issue by binkley** [micronaut-projects/micronaut-test#54]
I'm looking in `micronaut-test-junit5-1.1.0.RC1-sources.jar!/io/micronaut/test/extensions/junit5/MicronautJunit5Extension.java` from the 1.2.0 snapshot, and am confused with this:
```
    @Override
    public void afterTestExecution(ExtensionContext context) throws Exception {
        commit();
        rollback();
    }
```
Why does it both commit and rollback?  I would have expected it to just rollback.

In my tests, I'm manually rolling back in each test.  Is this the wrong approach?

----

If it should just rollback (as my intuition suggests to me), I'm happy to submit a PR for the change.

**Comment by graemerocher** [comment]
Yeah probably a bug, PRs welcome

**Comment by binkley** [comment]
Apologies for being slow getting to this.  I'm looking for a test around this behavior, and not finding it.  Some hints (or pointer to a README) would help.  Thanks!

**Comment by ajurasz** [comment]
@binkley please, take a look at conditions inside `commit` and `rollback` methods:

https://github.com/micronaut-projects/micronaut-test/blob/master/test-core/src/main/java/io/micronaut/test/extensions/AbstractMicronautExtension.java#L78:L79

https://github.com/micronaut-projects/micronaut-test/blob/master/test-core/src/main/java/io/micronaut/test/extensions/AbstractMicronautExtension.java#L89:L90

Depending on the value set for `rollback` parameter in `MicronautTest` annotation only one of these will be executed.

So I would say that all is good.

**Comment by binkley** [comment]
@ajurasz Oh, how magical!  :)  Glad to hear.

I investigated this as my Micrometer tests were not rolling back my transaction during unit tests.  I spotted the `commit()` and thought ... _Aha!_.

I'm using Kotlin Exposed library with Micrometer, so perhaps there is some interaction issue there.

Thanks!
