### ISSUE TITLE
Micronaut and Kotlintest

### ISSUE THREAD

**Issue by Kerooker** [micronaut-projects/micronaut-test#55]
Hey guys!

I'm one of the commiters at KotlinTest.

I created [this issue](https://github.com/kotlintest/kotlintest/issues/911) at KotlinTest, and when I came here to check how I could do it, I saw you guys has the implementation already. It was a great surprise!

If you guys need any help with this, feel free to reach out for us :D

**Comment by graemerocher** [comment]
@Kerooker thanks! @jameskleeh actually wrote the extension. It would be good if you could review what we have done and let us know if anything can be improved. The code is here https://github.com/micronaut-projects/micronaut-test/tree/master/test-kotlintest/src/main/kotlin/io/micronaut/test/extensions/kotlintest

**Comment by Kerooker** [comment]
Well, there is a typo on the class name. `Micornaut`

**Comment by graemerocher** [comment]
lol, good point 😂

**Comment by beedub** [comment]
I'm getting errors trying to use the kotlintest extension in my own project, and also seeing similar errors when trying to run the tests within this project. Eg. when running `MathMockServiceTest`

```
io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [io.micronaut.test.kotlintest.MathMockServiceTest] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
```

Any ideas @Kerooker or @jameskleeh ?

**Comment by jameskleeh** [comment]
Ensure your running with gradle. Kapt doesn’t work with the ide compiler

**Comment by beedub** [comment]
Works now. Thanks @jameskleeh

**Comment by graemerocher** [comment]
Closing this, thanks for reaching out if there are any other changes related to Kotlin test let us know.
