### ISSUE TITLE
Java project with Spock tests has errors in Eclipse

### ISSUE THREAD

**Issue by esocode** [micronaut-projects/micronaut-test#57]
Is there a working example for a Java micronaut project with Spock tests somewhere? I have tried to build such based on a micronaut CLI project and the MathService example from the documentation. After some tries I got the tests to run with Gradle on the command line, but when importing in Eclipse I get an error message in the Groovy test class (which is annotated with @MicronautTest):
```
Groovy:Groovy compiler error: exception in phase 'semantic analysis' in source unit 'MathServiceSpec.groovy' No such class: org.junit.jupiter.api.extension.ExtendWith
```
If I remove the `@MicronautTest` annotation or add the missing junit.jupiter API as a dependency the error disappears but then the test execution in Gradle fails. Test execution in Eclipse doesn't work at all.

My dependencies: 
```groovy
dependencies {
    annotationProcessor "io.micronaut:micronaut-inject-java"
    annotationProcessor "io.micronaut:micronaut-validation"

    compile "io.micronaut:micronaut-inject"
    compile "io.micronaut:micronaut-validation"
    compile "io.micronaut:micronaut-runtime"
    compile "io.micronaut:micronaut-http-client"
    compile "io.micronaut:micronaut-http-server-netty"
    
    testCompile "io.micronaut:micronaut-inject-groovy"
    testCompile "io.micronaut.test:micronaut-test-spock"
    testCompile "org.spockframework:spock-core:1.3-groovy-2.5"
}
```

**Comment by graemerocher** [comment]
combining Spock and Java requires using the GMaven Plus maven plugin instead of the Eclipse compiler if I recall

**Comment by esocode** [comment]
Sorry, my report was a bit imprecise as generic Spock tests are working in my project. The problem occurs when I try to create a Micronaut-specific Spock test with the `@MicronautTest` annotation which is not working for tests in the described Java/Groovy setup. As you can see from the error message the annotation causes a dependency to the `org.junit.jupiter` which is not present with the default dependency resolution. As spock is using JUnit 4 I'm wondering if maybe the bug lies in `micronaut-test-spock` relying on some JUnit 5 code?

**Comment by graemerocher** [comment]
It does feature references to junit5 annotations if they are not on the classpath but these should not cause an issue unless something else weird is going on

**Comment by jameskleeh** [comment]
I've seen an issue where both junit and spock are on the classpath, but only micronaut-test-junit or micronaut-test-spock is on the classpath. Please upload an example that reproduces the issue

**Comment by esocode** [comment]
Sorry, I have no such example availabe. After experiencing this I switched to JUnit 5 for testing in my Micronaut projects that I created afterwards.
