### ISSUE TITLE
Remove Kotest 4

### ISSUE THREAD

**Issue by wetted** [micronaut-projects/micronaut-test#643]
### Issue description

The upgrade to Kotlin 1.7.x for Micronaut 4 introduces some breaking changes to Kotest 4. We should remove Kotest 4 for Micronaut 4. 

see https://github.com/kotest/kotest/issues/2960

**Comment by sdelamo** [comment]
we need to do this @wetted

**Comment by wetted** [comment]
https://github.com/micronaut-projects/micronaut-test/pull/657
https://github.com/micronaut-projects/micronaut-test/pull/668
