### ISSUE TITLE
Update micronaut-spring once we have a snapshot for 4.0.0

### ISSUE THREAD

**Issue by timyates** [micronaut-projects/micronaut-test#693]
https://github.com/micronaut-projects/micronaut-test/blob/d311f1352de2058c189a958630f7d93953d10b50/gradle/libs.versions.toml#L17

**Comment by sdelamo** [comment]
closed via https://github.com/micronaut-projects/micronaut-test/commit/da77dd7a473367dcd404154f592f883fe8c674b5
