### ISSUE TITLE
Spock Stub methods returning null within a Lambda

### ISSUE THREAD

**Issue by philippreston** [micronaut-projects/micronaut-test#72]
So the issue I am seeing is as follows.  I have a Service class that is under test, and as part of that am injecting a number of MockBeans for testing the interactions.  So creating the MockBean as follows:

```groovy
@MockBean(SignupNotificationClient)
    SignupNotificationClient signupNotificationClient() {
        Mock(SignupNotificationClient)
    }
```

I have defined a stub method which returns an object, as part of my test:

```groovy
        and: "a publisher for the email send"
        boolean emailSent = false
        Mono<Void> sendEmail = Mono.empty().doOnSubscribe({ emailSent = true}).then()

        then: "should not be found in the database"
        ...
        signupNotificationClient.send(_, _) >>  sendEmail
```

This is injected into the Service class which I am testing.  

```java
 @Inject
    SignupNotificationClient notificationClient;
```

So the issue I am seeing is that when this method is called within a lambda - the method will return null.   

So I have stopped in the debugger to investigate what was happening.  So my code looks like this:

```java
return companyExists(cmd.getOrgName(), cmd.getOrgEntity(), cmd.getEmail())
                .flatMap(createOrError(cmd.getFirstName(),
                        cmd.getLastName(),
                        cmd.getEmail(),
                        cmd.getOrgEntity(),
                        cmd.getOrgName()))
                .doOnSuccess((signUp) -> {
                    createWelcomeMessage(cmd.getEmail(), cmd.getOrgName())
                            .subscribeOn(Schedulers.parallel())
                            .subscribe();
                });
```

So if I stop on the first line here (i.e. at the `return`) I can use the debugger and call `notificationClient.send` as many times as I want and get the result back as defined in my test stub.

However, you can see the `doOnSuccess` method - which uses a lambda, and within it calls the `createWelcomeMessage`.  This method is where the notificationClient.send is actually sent.. (irrelevant stuff stripped out)

```java
private Mono<Void> createWelcomeMessage(String email, String company) {
        ...
        try {
            ...
            return notificationClient.send(UUID.randomUUID().toString(), message);
        }
        catch (NotificationMessageException e) {
            throw Exceptions.propagate(e);
        }
    }
```

When this method is called here - it returns null.  A couple of things I noticed about this is that first of all - it's definitely the same object as I was calling outside of the lambda as is called inside the lambda (as viewing in the debugger).  The other thing is that the method on the Mock is definitely available as its returning `null` rather than throwing no method.

This is one example - but been able to see this with other Injected MockBeans.
 
Using 1.2.0 BOM (although also tried spock 1.3)

Any thoughts?

Many Thanks

Phil

**Comment by philippreston** [comment]
Should say this issue is only when running the test.  It actually works fine when running the application.

My current workaround is his code (declaring the publisher outside of the lambda):

```java
Mono<Void> welcomeMessage = createWelcomeMessage(cmd.getEmail(), cmd.getOrgName());

        return companyExists(cmd.getOrgName(), cmd.getOrgEntity(), cmd.getEmail())
                .flatMap(createOrError(cmd.getFirstName(),
                        cmd.getLastName(),
                        cmd.getEmail(),
                        cmd.getOrgEntity(),
                        cmd.getOrgName()))
                .doOnSuccess((signUp) -> {

                    welcomeMessage.subscribeOn(Schedulers.parallel())
                                  .subscribe();
                });```

**Comment by philippreston** [comment]
Hey 

I have managed to recreate this and have uploaded the code to https://github.com/philippreston/micronaut-test-issue-seventy-two

Simply run `./gradlew build`

You'll see that there are three tests:

- test in lambda :red_circle:
- test in lambda (no step verifier)  :white_check_mark:
- test outside lambda :white_check_mark:

Test in Lambda fails when using the StepVerfier - which is the same of my application (currently backing out using that for tests in the interim).

Let me know if this helps.

Thanks

Phil

**Comment by graemerocher** [comment]
Doubt it is related to the Lambda. I imagine it is threading with Mono/reactor
