### ISSUE TITLE
After 1st test finishes, subsequent tests don't trigger the bean listeners

### ISSUE THREAD

**Issue by mcanalesmayo** [micronaut-projects/micronaut-test#739]
### Expected Behavior

When running more than one `@MicronautTest` annotated tests, I'd expect all of them to trigger the bean listeners, but only the 1st test does.

### Actual Behaviour

After the 1st test finishes, subsequent tests don't trigger the bean listeners.
From what I could see while debugging, after the 1st test finishes its bean context gets cleaned up (therefore the bean listeners are removed), but the same bean context is then reused for the 2nd test for some reason (which I guess it's not expected).
Running each test individually works fine, e.g. `./gradlew test --tests "package.with.my.Test"` but running everything as `./gradlew test` fails because of the above mentioned behavior.
This was not happening in 3.4.x and I can only see this behavior in 3.5.x.

### Steps To Reproduce

Code and instructions to reproduce here: https://github.com/mcanalesmayo/micronaut-bug-3.5.x-bean-listener

### Environment Information

- Operating system: linux or macOS
- JDK: 11

### Example Application

https://github.com/mcanalesmayo/micronaut-bug-3.5.x-bean-listener

### Version

3.5.x

**Comment by graemerocher** [comment]
doubt this is a bug, you probably need to specify `refreshContext` to `@MicronautTest`

**Comment by mcanalesmayo** [comment]
@graemerocher as far as I understand, `rebuildContext` is for refreshing the context for each test **within** a `@MicronautTest` class
the issue I saw when debugging is that the context created from one `@MicronautTest` class is reused in the tests of another `@MicronautTest` class
please see the tests in the example repository: https://github.com/mcanalesmayo/micronaut-bug-3.5.x-bean-listener/tree/master/src/test/java/com/example

**Comment by graemerocher** [comment]
no this is not accurate, a single context is shared across all tests unless something changes that triggers the rebuild of the context (like specifying different configuration or using `rebuildContext`)

**Comment by mcanalesmayo** [comment]
I'll close this ticket then, as you clarified it's expected behavior.

Thanks for your support.
