### ISSUE TITLE
@Inject not working in JUnit5 test

### ISSUE THREAD

**Issue by 4ntoine** [micronaut-projects/micronaut-test#79]
Here are the [sources](https://github.com/4ntoine/NotesServerApp/blob/issue-6-micronaut-test/app-micronaut/src/test/kotlin/name/antonsmirnov/notes/controller/rest/AddNoteControllerTest.kt#L36).

As it's assumed by `@Inject` [controller](https://github.com/4ntoine/NotesServerApp/blob/issue-6-micronaut-test/app-micronaut/src/test/kotlin/name/antonsmirnov/notes/controller/rest/AddNoteControllerTest.kt#L19) is meant to be injected.

However it's null [here](https://github.com/4ntoine/NotesServerApp/blob/issue-6-micronaut-test/app-micronaut/src/test/kotlin/name/antonsmirnov/notes/controller/rest/AddNoteControllerTest.kt#L37).

I'm running in Intellij idea.

BTW the test if meant to be failing as strings are built in different way ([expected](https://github.com/4ntoine/NotesServerApp/blob/issue-6-micronaut-test/app-micronaut/src/test/kotlin/name/antonsmirnov/notes/controller/rest/AddNoteControllerTest.kt#L38) vs [actual](https://github.com/4ntoine/NotesServerApp/blob/issue-6-micronaut-test/app-micronaut/src/test/kotlin/name/antonsmirnov/notes/controller/rest/AddNoteControllerTest.kt#L25)).

If running from cmd (`./gradlew :app-micronaut:test`) the tests are not run.

BTW i've tried to instantiate both [use case](https://github.com/4ntoine/NotesServerApp/blob/issue-6-micronaut-test/app-micronaut/src/test/kotlin/name/antonsmirnov/notes/controller/rest/AddNoteControllerTest.kt#L22) (required for instantiating of controller) and [controller](https://github.com/4ntoine/NotesServerApp/blob/issue-6-micronaut-test/app-micronaut/src/test/kotlin/name/antonsmirnov/notes/controller/rest/AddNoteControllerTest.kt#L31) itself.

What's wrong?

**Comment by frankyfish** [comment]
Hi @4ntoine. I was about to say that I have the same issue when I saw that i have a couple of junit dependencies in my pom.xml. @Test annotation I was using in my test was from org.junit while there was another one from org.junit.jupiter.api.
AFAIU from here: https://micronaut-projects.github.io/micronaut-test/latest/guide/index.html#junit5
The one from jupiter has to be used.

**Comment by 4ntoine** [comment]
Hi, @frankyfish 

Thanks for pointing.
Indeed, i've used "org.junit.Test" annotation. However after changing it to "orj.junit.jupiter.api" the behaviour changed. Now i'm getting the following error:
```
org.junit.jupiter.engine.execution.ConditionEvaluationException: Failed to evaluate condition [io.micronaut.test.extensions.junit5.MicronautJunit5Extension]: @MicronautTest used on test but no bean definition for the test present. This error indicates a misconfigured build or IDE. Please add the 'micronaut-inject-java' annotation processor to your test processor path (for Java this is the testAnnotationProcessor scope, for Kotlin kaptTest and for Groovy testCompile). See the documentation for reference: https://micronaut-projects.github.io/micronaut-test/latest/guide/
```

The problem is that i do have `kapt "io.micronaut:micronaut-inject-java"` in my build.gradle.

So configuring micronaut seems to be damn hard

**Comment by jameskleeh** [comment]
There doesn't seem to be any issue here related to Micronaut. I removed the `@MicronautTest` annotation and the test still doesn't even run for me. 

```
> No tests found for given includes: [name.antonsmirnov.notes.controller.rest.AddNoteControllerTest](filter.includeTestsMatching)
```

If you'd like us to pursue this further upload a sample application that is as simple as possible to rule out any outside factors.
