### ISSUE TITLE
MicronautTest (Spock) with Testcontainers 

### ISSUE THREAD

**Issue by mkfuri** [micronaut-projects/micronaut-test#80]
I'm wanting to test my DB (postgres)  with Testcontainers, but I can't configurate the new datasource properties of my PostgreSQLContainer.

I'm implementing _TestPropertyProvider_ interface and the class is annotated with _@MicronautTest_, _@Testcontainers_ and _@TestInstance(TestInstance.Lifecycle.PER_CLASS)_

My code is 

```
@MicronautTest
@Testcontainers
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class QuotationServiceImplSpec extends Specification implements TestPropertyProvider {

    @Shared
    PostgreSQLContainer postgreSQLContainer = new PostgreSQLContainer()
            .withDatabaseName("finprop")
            .withUsername("finprop")
            .withPassword("f1npr0p")

    @Inject
    QuotationServiceImpl quotationService

    @Inject
    EntityManager entityManager

    @Override
    Map<String, String> getProperties() {
        return Collections.singletonMap("datasources.default.url", postgreSQLContainer.jdbcUrl)
    }

    def "Test insert Quotation with correct data into DB"(){
        given: "An Existing Quotation Type"
        QuotationType quotationType = entityManager.persist(new QuotationType(name: "Quotation Type Test"))

        and: "An existing credit type"
        CreditType creditType = entityManager.persist(new CreditType(name: "Credit Type Test"))

        and: "A Quotation with all correct field fill"
        Quotation quotationActual = new Quotation(expenses: 4000, rent: 15000, quotationType: quotationType,
                creditType: creditType)

        when: "Saved the quotation into DB"
        Quotation quotationExpected = quotationService.save(quotationActual)

        then: "The quotation was saved into DB"
        quotationExpected.id
    }
}
```

But when a launch my test the _IllegalStateException_ was thrown

```
java.lang.IllegalStateException: Mapped port can only be obtained after the container is started
	at org.testcontainers.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:174)
	at org.testcontainers.containers.ContainerState.getMappedPort(ContainerState.java:107)
	at org.testcontainers.containers.PostgreSQLContainer.getJdbcUrl(PostgreSQLContainer.java:62)
	at groovy.lang.MetaBeanProperty.getProperty(MetaBeanProperty.java:59)
	at com.navent.finprop.credit.services.QuotationServiceImplSpec.getProperties(QuotationServiceImplSpec.groovy:32)
	at io.micronaut.test.extensions.spock.MicronautSpockExtension.resolveTestProperties(MicronautSpockExtension.java:141)
	at io.micronaut.test.extensions.spock.MicronautSpockExtension.resolveTestProperties(MicronautSpockExtension.java:52)
	at io.micronaut.test.extensions.AbstractMicronautExtension.beforeClass(AbstractMicronautExtension.java:157)
	at io.micronaut.test.extensions.spock.MicronautSpockExtension.lambda$visitSpecAnnotation$0(MicronautSpockExtension.java:61)
```

I don't know if I'm missing any configuration. I followed #32 and #26

**Comment by mkfuri** [comment]
Close because isn't a Micronaut problem

**Comment by micheal-hill** [comment]
I'm facing the same problem using a very similar setup. Problem occurs for me because the container is only initialised in the `setup` or `setupSpec` method; but Micronaut is building the datasource when the test is loaded (at which point the jdbc url is not known).
Is it possible to have the datasource configured as part of a `setup` or `setupSpec` method? Therefore, datasource configuration could be deferred until after the DB has been created?

**Comment by mkfuri** [comment]
@micheal-hill I removed `@testcontainers` and make static the variable postgreSQLContainer without `@Shared`.

```
abstract class RealDataBaseTestSpec extends Specification implements TestPropertyProvider{

    static MySQLContainer mySQLContainer = new MySQLContainer()
            .withDatabaseName("xxxx")
            .withUsername("xxxx")
            .withPassword("xxxx")

    static {
        mySQLContainer.start()
    }

    @Override
    Map<String, String> getProperties() {
        def properties = ["datasources.default.url": mySQLContainer.jdbcUrl,
                          "datasources.default.driverClassName": mySQLContainer.driverClassName,
                          "datasources.default.username": mySQLContainer.username,
                          "datasources.default.password": mySQLContainer.password
        ]
        return properties
    }

    def setupSpec(){
        Flyway.configure()
                .dataSource(mySQLContainer.jdbcUrl, mySQLContainer.username, mySQLContainer.password)
                .load().migrate()
    }
}
```

**Comment by musketyr** [comment]
@graemerocher this was the issue I was referring to during today's Twitch session.  maybe @bsideup or @kiview would know more and maybe they would have an solution to this

**Comment by bsideup** [comment]
@musketyr thanks for the ping!

@mkfuri's snipped looks good already, although I would even consider removing the `static {}` block and doing `start()` in `getProperties()` (or `setupSpec`, depending on which executed first... or both :D), just to start it only when needed.

**Comment by musketyr** [comment]
well, it's a way to go but it's quite counterintuitive. if you're new to MN + TC testing you will simply take the examples from MN and TC websites and then you are lost until you google this solution (been there with my colleagues).

if I understand it well then this is a sort of issue of Spock extensions order?

**Comment by graemerocher** [comment]
Gotta say this works a lot better in JUNit 5 with the `@Testcontainers` and `@Container` annotations managing this for you

**Comment by musketyr** [comment]
just checking the code it seems to me that the simple fix would be to ensure that the `@Testcontainers` extension runs before `@MicronautTest` one.

@leonard84 is there any way how to change the order in which the extensions are applied? does it depend on the order in which are the annotations written in the class?

**Comment by leonard84** [comment]
No spock doesn't support ordering of extensions or interceptors https://github.com/spockframework/spock/issues/646

**Comment by musketyr** [comment]
@leonard84 what about having a _meta_ extensions to which will have the order defined?

```
@Extensions([
    @Testcontainers,
    @MicronautTest,
])
```

**Comment by leonard84** [comment]
The problem isn't really the extension order, but the interceptor order, which would be indirectly affected by extension order. Also this issue is the wrong place for this discussion.
