### ISSUE TITLE
Inaccessible Object Exception in Unit Test

### ISSUE THREAD

**Issue by satya-devloper** [micronaut-projects/micronaut-test#837]
### Expected Behavior

Unit test should not be affected after change from Micronaut 3 to micronaut 4

### Actual Behaviour

I have switched from micraonut 3 to Micronaut 4, so I have to use java. 17 now as per documentation and earlier I was using java 14. 
So Ideally all the test should pass, but what I can see that wherever I m using withEnvVariable function in unit test, it is failing with execution Inaccessible Object Exception

### Steps To Reproduce

public void EnvironmentVariablesTest {
@test
public void setEnvironmentVariable() {
String value = withEnvironmentVariable("name", "value")
.execute(() -> System.getenv("name"));
assertEquals("value", value);
}
}

when I tried to run this sample unit test only getting issue "Unable to make field private final java.util.Map java.util.Collections$UnmodifiableMap.m accessible: module java.base does not "opens java.util" to unnamed module @7549926"

After going through google search I found that this issue is of java17 which microanut 4 is also using
I tries adding this in build.gradle
test {
jvmArgs ["–add-opens java.base/java.lang=ALL-UNNAMED"]
systemProperty 'add-opens', 'java.base/java.lang=ALL-UNNAMED'
systemProperty 'add-opens', 'java.base/java.util=ALL-UNNAMED'
}

but still same issue

### Environment Information

Mac
java 17.0.8

### Version

4.0.1

**Comment by satya-devloper** [comment]
[micronautguid-sample.zip](https://github.com/micronaut-projects/micronaut-test/files/12303510/micronautguid-sample.zip)

**Comment by satya-devloper** [comment]
I have made necessary changes for micraonut4 version in build.gradle which I m using in my project
command := ./gradlew build -i

**Comment by satya-devloper** [comment]
@dstepanov , plz let me know if anything missing

**Comment by satya-devloper** [comment]
@dstepanov , Any Update on this issue as our code is breaking after upgrade

**Comment by dstepanov** [comment]
I'm sorry, this has nothing to do with Micronaut. The problem is with `systemlambda` which is using reflection to access JDK classes, which is not allowed by default in Java 7.
There is an issue https://github.com/stefanbirkner/system-lambda/issues/23
