### ISSUE TITLE
Flaky Tests in Micronaut solved by adding a dummy test?

### ISSUE THREAD

**Issue by rdehuyss** [micronaut-projects/micronaut-test#872]
### Expected Behavior

I'm Ronald, the creator of [JobRunr](https://github.com/jobrunr/jobrunr). With Micronaut, I have often test failures that I do not understand. It is solved by adding another dummy test first and running the tests in alphabetical order.

I expect my tests with `@MicronautTest` to be independent from each other.

### Actual Behaviour

Often, the first test fails.

### Steps To Reproduce

1. Clone and checkout https://github.com/jobrunr/jobrunr
2. Run the test `JobRunrFactoryTest` in Framework Support > jobrunr-micronaut-feature. Tests are green.
3. Remove the first test (see below) and run the same test `JobRunrFactoryTest` again. There are test failures.
```
    @Test
    void aFirstTestThatReloadsTheContextToMakeFlakyTestWork() {
        assertThat(context).hasSingleBean(StorageProvider.class);
    }
```

### Environment Information

- JVM 
- Mac OS 21

### Example Application

https://github.com/jobrunr/jobrunr

### Version

4.1.4

**Comment by dstepanov** [comment]
Any idea why the project cannot be imported into the Intellij:
```
:framework-support:jobrunr-quarkus-extension:tests:integrationTest: Could not resolve project :core.
Required by:
    project :framework-support:jobrunr-quarkus-extension:tests

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

**Comment by rdehuyss** [comment]
To be honest, no. For me the bug is intermittent and I've already reached out to the Quarkus team for it... 

You can unload that project in Intellij or remove `framework-support:jobrunr-quarkus-extension:tests` from `settings.gradle`.

And most of all: thanks for having such a quick look! Appreciate it! ❤️

**Comment by dstepanov** [comment]
Was it flaky or just not working?

**Comment by rdehuyss** [comment]
Well, I think if I read the title of your PR that you nailed the issue. 

The problem is that Intellij/gradle runs the test in random order, causing me to think that test were flaky. However, in hindsight it was solved by running the test in a certain order with the extra first test.

To answer your question: Option B ☺️

**Comment by nicoraynaud** [comment]
Maybe I am joining the party a bit late but: wouldn't using `@Order` fix your issue ? It's not a good pattern but is sometimes necessary 🤷

**Comment by rdehuyss** [comment]
This is what I already did but even then the first test failed always. 

And, as a maintainer of a distributed job scheduling library, I have come to like the chaos of tests not running in the same order. It brought up some concurrency issues which would not have been found if the order of the tests would have been the same always.

**Comment by sdelamo** [comment]
I think ordered it is not guaranteed unless you use `@Order`. I don't think it is Micronaut related. 

Our cache guide has an example of `@Order` and Junit5 
https://guides.micronaut.io/latest/micronaut-cache-gradle-java.html#test-the-cache
