### ISSUE TITLE
While testing a controller, when an exception is thrown the exception handler is not handling the exception

### ISSUE THREAD

**Issue by azhar243** [micronaut-projects/micronaut-test#89]
I've written a simple web application in which when an exception is thrown, An exception handler will handle that and returns an Api Error response. 

When I try to write a Junit test for an exception scenario to test exception handler, Instead of exception handler handling the exception and returning the Api Error Response, HttpClientResponseException is thrown.

Because of the above behaviour, I'm not able to test the exception handlers. Any help would be appreciated.

**Comment by graemerocher** [comment]
you can catch the exception and if you have set `errorType` then the response body is available on the `response` object referenced by `HttpClientResponseException`. If you have any other doubts please ask questions in https://gitter.im/micronautfw
