### ISSUE TITLE
Improve "missing @MicronautTest" annotation error message

### ISSUE THREAD

**Issue by nbrugger-tgm** [micronaut-projects/micronaut-test#894]
### Expected Behavior

When using @MicronautTest as meta annotation it should work
```java
@Inherited
@Retention(RUNTIME)
@MicronautTest(environments = "integration")
public @interface DatabaseTest {}
```

### Actual Behaviour

```
org.junit.jupiter.engine.execution.ConditionEvaluationException: Failed to evaluate condition [io.micronaut.test.extensions.junit5.MicronautJunit5Extension]: @MicronautTest used on test but no bean definition for the test present. This error indicates a misconfigured build or IDE. Please add the 'micronaut-inject-java' annotation processor to your test processor path (for Java this is the testAnnotationProcessor scope, for Kotlin kaptTest and for Groovy testCompile). See the documentation for reference: https://micronaut-projects.github.io/micronaut-test/latest/guide/
```

### Steps To Reproduce

1. `git clone https://github.com/nbrugger-tgm/micronaut-reproductions`
2. `cd micronaut-reproductions`
3. `./gradlew :894:test`

### Additional Info
When using the @MicronautTest directly on the test it works

### Environment Information

- JDK: 17, 20
- OS: Linux/Ubuntu

### Version

4.10.1

**Comment by nbrugger-tgm** [comment]
This is a weird one; The generation didn't work because of the
```groovy
micronaut {
    processing {
        incremental(true)
        annotations("com.example.*")
    }
}
```

the "com.example.*" was wrong. But i do not understand why it behaves as it does

- Using an `@MockBean` re-enables` the tests again
- Using `@Nested` makes it work again

Maybe improving the error message or adding a hint would be good

**Comment by nbrugger-tgm** [comment]
Reproducer: https://github.com/micronaut-projects/micronaut-test/issues/894

**Comment by timyates** [comment]
I suspect it's some interaction with Lombok in your tests...

If instead of using `@AllArgsConstructor` in the `DemoTest` class, I use the recommended method of

```diff
-@AllArgsConstructor
 @MetaAnnotationWithMicronautTest
 class DemoTest {
-    private final Application application;
+
+    @Inject
+    Application application;
```

It seems to work...  Do you see the same?

**Comment by nbrugger-tgm** [comment]
Ok thank you for the explanation. I think for documentation purposes this issue is fine since its an edgecase on top of a user error (mine).

That said a "also check the micronaut plugin annotation processing package setting" would probably still be nice.

Its up to you if this should be closed or stays open for processing. I could do the pr if it is wanted

**Comment by timyates** [comment]
@nbrugger-tgm I pushed this change to mention the property (it's different in Maven and Gradle) https://github.com/micronaut-projects/micronaut-test/pull/957 Is that good for you?

**Comment by nbrugger-tgm** [comment]
Looks good to me

Thank you
