### ISSUE TITLE
Setting `resolveParameters = false` breaks constructor injection (junit5)

### ISSUE THREAD

**Issue by rorueda** [micronaut-projects/micronaut-test#898]
### Expected Behavior

As I understand, setting `resolveParameters = false` should only act on methods.

### Actual Behaviour

It also acts on constructors.

### Example Application

See modified test: https://github.com/micronaut-projects/micronaut-test/compare/master...rorueda:micronaut-test:resolve-parameters-fix

### Version

4.x

**Comment by rorueda** [comment]
I can open a PR with the change, but Just want to make sure my understanding is correct.

**Comment by graemerocher** [comment]
PRs welcome, looks like your understanding is correct
