### ISSUE TITLE
Stopping the application context in a test causes the TestSqlAnnotationHandler to throw an exception

### ISSUE THREAD

**Issue by PhilHardwick** [micronaut-projects/micronaut-test#901]
### Expected Behavior

When you @Inject an ApplicationContext in a test and stop it during the test, it should not error when ending the test.

### Actual Behaviour

TestSqlAnnotationHandler throws a BeanNotFoundException

### Example Application

https://github.com/micronaut-projects/micronaut-test/compare/master...PhilHardwick:micronaut-test:application-stop-test?expand=1

### Version

4.1.0

I'm happy to contribute a fix here, just need to discuss what the fix should be. I'm unsure about making the sql annotation handler silently fail when it tries to use a stopped context.

**Comment by timyates** [comment]
@PhilHardwick Thanks! I raised a PR using your test (with you as co-author) 👍
