### ISSUE TITLE
Spock Unroll tests rollback regression

### ISSUE THREAD

**Issue by mattlong-finocomp** [micronaut-projects/micronaut-test#911]
### Expected Behavior

When writing a Spock test that has Unroll semantics (which is now implicit) performs DB operations, the transaction should be rolled back for each iteration that is performed.
This used to be the case in Micronaut 3.

### Actual Behaviour

The transaction is not rolled back until after all iterations of the Unroll are performed.
The transaction is rolled back for each iteration if the MicronautTest annotation has a transactionMode of SINGLE_TRANSACTION.

### Steps To Reproduce

Run the following tests in the linked example application:
UnrollRollbackSpec - proves that the transaction isn't rolled back between iterations
UnrollRollbackSingleTransactionSpec - proves that the transaction is rolled back between iterations when transactionMode is SINGLE_TRANSACTION

### Environment Information

OS: Pop!OS 22.04
Java: 17

### Example Application

https://github.com/mattlong-finocomp/micronaut-unroll-rollback

### Version

4.2.1

**Comment by timyates** [comment]
@mattlong-finocomp Thank you so much for the report and the reproducer! This is fixed by https://github.com/micronaut-projects/micronaut-test/pull/953 and will be in the forthcoming micronaut-test 4.2.1 and 4.3.0 👍
