### ISSUE TITLE
@MicronautTest does not work properly with mockk

### ISSUE THREAD

**Issue by 22dasi1bwi** [micronaut-projects/micronaut-test#92]
### Steps to Reproduce

1. Clone https://github.com/22dasi1bwi/micronaut-test-mockk
2. Inspect the code
3. Run the test
4. See the mismatch

### Expected Behaviour

I'm using _mockk_ in a _@MicronautTest_ in order to mock the underlying repository. The repository should be mocked and the data should actually be retrieved from a Client instead.

### Actual Behaviour

Although I mocked the repository, the data is still retrieved from it instead of the Client.

### Environment Information

- **Operating System**:
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux

- **Micronaut Version:** 1.2.6
- **JDK Version:**
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)

### Example Application

- https://github.com/22dasi1bwi/micronaut-test-mockk

**Comment by alvarosanchez** [comment]
You are mixing JUnit 5 (in the test) with Kotlintest (in the build). Mockk is only going to work with Kotlintest, so you will need to rewrite your tests to remove JUnit references and use [any of their supported styles](https://github.com/kotlintest/kotlintest/blob/master/doc/styles.md).

Some examples:
* Using Kotlintest's `AnnotationSpec`: https://github.com/micronaut-projects/micronaut-test/blob/master/test-kotlintest/src/test/kotlin/io/micronaut/test/kotlintest/PropertyValueRequiresTest.kt
* Using Mockk: https://github.com/micronaut-projects/micronaut-test/blob/master/test-kotlintest/src/test/kotlin/io/micronaut/test/kotlintest/MathMockServiceTest.kt
